class ExportI18n
  def initialize(task_name, keys)
    @task = task_name
    @keys = Array(keys)
  end

  def to(dest_file)
    dest_file = Rails.root.join(dest_file)
    write_to_file dest_file, locale_data
    format_file   dest_file
    puts "#{@task}: OK"
  end

  private

  def write_to_file(dest, data)
    dest.open("w") do |f|
      f.puts "/** @file Generated by `rake js:i18n:#{@task}` - DO NOT EDIT */"
      f.puts
      f.write "export default "
      f.puts JSON.pretty_generate(data)
    end
  end

  def format_file(dest)
    eslint = Rails.root.join("node_modules/.bin/eslint")
    return unless eslint.exist?

    out = IO.popen [eslint, "--fix", dest].map(&:to_s), "r", err: %i[child out], &:read

    if (code = $?.exitstatus) && code != 0
      $stderr.puts "eslint failed with status #{code}:"
      $stderr.puts out
      raise "eslint failed"
    end
  end

  def locale_data
    @locale_data ||= I18n.available_locales.map.with_object({}) { |locale, result|
      result[locale] = @keys.map.with_object(Hash.new { |h, k| h[k] = {} }) { |key, translations|
        start       = I18n.t(key, locale: locale)
        root, *rest = key.split(".")

        # drop js prefix
        root = rest.shift if root == "js"

        translations[root].merge!(
          rest.reverse.inject(start) { |tree, k| { k => tree } },
        )
      }
    }
  end
end

namespace :js do
  desc "Re-generates i18n.js files"
  task i18n: %i[i18n:frontend i18n:admin]

  namespace :i18n do
    task frontend: :environment do
      ExportI18n.new(:frontend, %w[
        js.boat_booking
        js.bsp1_form
        js.contact_form
        js.drp
        js.facets
        js.footer
        js.header_search
        js.infinite_loading
        js.maps
        js.newsletter
        js.price_table
        js.reservation_form
        js.villa_booking
        js.villas_list
        countries
        state_names

        activerecord.attributes.villa.pool_orientation
        area_tags
        date.month_names
        footer.closing
        home.dynamic.slide
        shared.discount
        villas.cardinal_directions
      ]).to("app/javascript/i18n.js")
    end

    task admin: :environment do
      ExportI18n.new(:admin, %w[
        js.generic
        js.error_wrapper
        js.inquiry_editor
        js.villa_editor

        category_multiple_types
        admin.my_booking_pal.update_progress.steps
        admin.villa_check
      ]).to("app/javascript/admin/i18n.js")
    end
  end
end
