/** @file Generated by `rake js:i18n:admin` - DO NOT EDIT */

export default {
  "de": {
    "generic": {
      "add": "Hinzufügen",
      "delete": "Löschen",
      "remove": "Entfernen",
      "save": "Speichern",
      "cancel": "Abbrechen",
      "please_select": "Bitte wählen"
    },
    "error_wrapper": {
      "required": "muss ausgefüllt werden",
      "required_selection": "muss ausgewählt werden",
      "must_not_be_occupied": "ist bereits belegt",
      "must_match_category": "muss zur Preiskategorie passen"
    },
    "inquiry_editor": {
      "cancellation": {
        "heading": "Buchung/Anfrage stornieren",
        "create": "Storno anlegen",
        "error": "Stornierung konnte nicht angelegt werden",
        "unknown_error": "unbekannter fehler",
        "success": "Buchung/Anfrage %{number} erfolgreich storniert",
        "goto": {
          "index": "zurück zur Übersicht",
          "cancellation": "Storno anzeigen"
        },
        "reason": "Stornierungsgrund",
        "reason_hint": "Warum soll diese Anfrage storniert werden? Der Grund wird per E-Mail an die Eigentümer und Manager der Villa (und ggf. des Boots, sofern gebucht) weitergeleitet."
      },
      "uncancellation": {
        "heading": "Storno zurücknehmen",
        "description": "Wir versuchen aus dieser Stornierung eine Buchung zu rekonstruieren. Dabei ist es Möglich, dass der Buchungszeitraum mittlerweile von einer anderen Buchung belegt wurde. Eine solche Kollision muss manuell aufgelöst werden.",
        "create": "Buchung wiederherstellen",
        "error": "Buchung konnte nicht wiederhergestellt werden",
        "unknown_error": "unbekannter fehler",
        "success": "Buchung %{number} erfolgreich wiederhergestellt",
        "goto": {
          "index": "zurück zur Übersicht",
          "booking": "Buchung anzeigen"
        }
      },
      "note_mail": {
        "heading": "Hinweis: Es wurden Änderungen durchgeführt, die automatisch neue Benachrichtigungen an Eigentümer und Verwaltungen versenden:",
        "skip": "Dieses Mal keine Benachrichtigungen versenden.",
        "villa": {
          "id": "Die Villa wurde geändert. Eigentümer/Verwaltungen der vorherigen Villa bekommen eine Storno-Nachrichtung und Eigentümer/Verwaltungen der neuen Villa eine Buchungsbestätigung.",
          "dates": "Reisezeitraum der Villa wurde geändert."
        },
        "boat": {
          "added": "Es wurde ein Boot hinzugefügt. Eigentümer/Verwaltungen erhalten eine Buchungsbestätigung.",
          "removed": "Das Boot wurde entfernt. Eigentümer/Verwaltungen erhalten eine Stornierung.",
          "id": "Das Boot wurde geändert. Eigentümer/Verwaltungen des vorherigen Boots bekommen eine Storno-Nachrichtung und Eigentümer/Verwaltungen des neuen Boots eine Buchungsbestätigung.",
          "dates": "Mietzeitraum des Boots wurde geändert."
        }
      },
      "inquiry": {
        "objects": "Objekte",
        "range": "Zeitraum",
        "remote_data": {
          "loading": "Hole Belegungsdaten…",
          "load_error": "Fehler beim Laden der Belegungsdaten."
        },
        "villa": {
          "label": "Villa",
          "prices_info": [
            "EUR (+ USD) = Preise in EUR definiert, USD wird automatisch umgerechnet",
            "EUR + USD = Preise in EUR und USD definiert",
            "USD-only = Buchungen nur in USD möglich"
          ],
          "villa_missing": "bitte zuerst eine Villa auswählen"
        },
        "boat": {
          "label": "Boot",
          "inclusive": "Inklusiv-Boot, kann nicht geändert werden",
          "add": "Boot hinzufügen",
          "remove": "Boot aus der Buchung entfernen",
          "groups": {
            "optional": "der Villa zugeordnete Boote",
            "others": "weitere Boote",
            "inclusive": "Inklusiv-Boot der Villa",
            "hidden": "Boote aus Bestandsbuchungen"
          },
          "invalid": "Das Boot ist in dem gewählten Zeitraum nicht verfügbar"
        },
        "incomplete": "Bitte Haus und Zeitraum auswählen, danach werden die Felder für die Reiseteilnehmer eingeblendet.",
        "no_enough_travelers": "Es müssen mind. zwei Erwachsene Reiseteilnehmer ausgewählt sein.",
        "saving_failed": "Speichern fehlgeschlagen",
        "saving_no_possible": "speichern nicht möglich",
        "saving": "Speichere",
        "save": "Speichern"
      },
      "customer": {
        "label": "Kundendaten",
        "external": "externe Buchung",
        "external_hint": [
          "Dies ist eine Buchung über ein externes Portal wie z.B. airbnb und VRBO.",
          "Bei externen Buchungen werden keine automatisierten E-Mails versendet."
        ],
        "email": "E-Mail-Adresse",
        "phone": "Telefon",
        "locale": {
          "label": "Sprache",
          "de": "deutsch",
          "en": "englisch"
        },
        "currency": "Währung",
        "title": {
          "label": "Anrede",
          "m": "Herr",
          "f": "Frau"
        },
        "first_name": "Vorname",
        "last_name": "Nachname"
      },
      "traveler": {
        "label": "Reisende",
        "add": "Reisenden hinzufügen",
        "keep": "Rückgängig",
        "remove": "Entfernen",
        "first_name": "Vorname",
        "last_name": "Nachname",
        "category": "Preiskategorie",
        "born_on": "Geburtstag",
        "age_on_arrival": "Alter am Anreisetag",
        "age": "%{n} J.",
        "categories": {
          "adults": "Erwachsene",
          "children_under_6": "Kinder bis 6 J.",
          "children_under_12": "Kinder bis 12 J."
        },
        "category_not_available": {
          "abbr": "n.v.",
          "title": "nicht verfügbar: Haus hat Wochenpreise"
        }
      },
      "sidebar": {
        "label": "Buchungsdetails",
        "inquiry": {
          "label": "Anfrage",
          "created_at": "Anfrage/Angebot vom",
          "updated_at": "zuletzt geändert am",
          "booked_at": "verbindlich gebucht am",
          "cancelled_at": "storniert am"
        },
        "traveler": {
          "label": "Reisteteilnehmer",
          "unknown": "unbekannt",
          "born": "geb.",
          "birthday": "hat im Reisezeitraum Geburtstag"
        },
        "travel_insurance": {
          "label": "Reiseversicherung",
          "unknown": "unbekannt",
          "insured": "vorhanden",
          "not_insured": "nicht vorhanden"
        },
        "bookable": {
          "villa": "Villa",
          "boat": "Boot",
          "dates": "Zeitraum",
          "discounts": "Aufschläge/Rabatte"
        },
        "discounts": {
          "label": "Aufschlag/Rabatt bearbeiten",
          "category": "Kategorie",
          "dates": "Zeitraum",
          "apply_booking_dates": "Reisezeitraum übernehmen",
          "apply_dates": "übernehmen",
          "discount": "Aufschlag",
          "discount_hint": "Aufschläge positiv, Rabatte negativ, 0 zum Löschen",
          "reload_hint": "Nach dem Speichern wird die Preistabelle automasch neugeladen.",
          "high_season_dates": "Zeitraum",
          "high_season_loading": "Lade…",
          "high_season_not_found": "Keine Hochsaison zum Reisezeitraum gefunden.",
          "high_season_overlap": "Deckung",
          "high_season": "Hochsaison"
        }
      },
      "checked_discounts": "Villa oder Buchungszeitraum haben sich geändert. Alle Aufschläge/Rabatte wurden kontrolliert.",
      "common": {
        "local_validation_failed": "lokale Validierung fehlgeschlagen",
        "remote_validation_failed": "Server-Validierung fehlgeschlagen",
        "saved_successfully": "Buchungsdaten erfolgreich gespeichert",
        "no_server_response": "Keine Antwort vom Server"
      },
      "energy_cost": {
        "label": "Energiekosten-Berechnung",
        "options": {
          "defer": "bei Abrechnung festlegen",
          "usage": "Verbrauch abrechnen",
          "flat": "Pauschale",
          "included": "enthalten im Mietpreis"
        },
        "preset": "Vorgabe vom Haus",
        "override": "abweichender Wert",
        "legacy": "Bestandsbuchung"
      }
    },
    "villa_editor": {
      "save_btn": "Speichern",
      "cancel_btn": "Änderungen verwerfen",
      "nav": {
        "villa": {
          "label": "Villa-Details",
          "section_alias": "Details"
        },
        "tags": {
          "label": "Merkmale"
        },
        "additional_props": {
          "label": "Weitere Eigenschaften"
        },
        "prices": {
          "label": "Preise"
        },
        "images": {
          "label": "Fotos",
          "section_alias": "Medien"
        },
        "tours": {
          "label": "Touren v1",
          "section_alias": "Medien"
        },
        "pannellums": {
          "label": "Touren v2",
          "section_alias": "Medien"
        },
        "videos": {
          "label": "Videos"
        },
        "boats": {
          "label": "Boote"
        },
        "reviews": {
          "label": "Bewertungen"
        },
        "show": {
          "label": "Villa anzeigen"
        },
        "index": {
          "label": "zurück zur Übersicht"
        }
      },
      "section_heading": {
        "edit": "%{label} bearbeiten",
        "create": "%{label} anlegen"
      },
      "details": {
        "status": "Status",
        "active": "aktiv?",
        "buyable": "zu verkaufen?",
        "routing": {
          "label": "Routing",
          "desc": "Auf welchen Domains ist diese Villa sichtbar?"
        },
        "name": "Name",
        "area": "Wohnfläche",
        "pool_orientation": "Ausrichtung Pool",
        "build_year": "Baujahr",
        "last_renovation": "Zuletzt renoviert",
        "safe_code": "Safe-Code",
        "safe_code_hint": "Safe-Code und Telefonnummer werden in die Reiseantrittsmail eingefügt. Diese Eingabefelder sind NICHT für Text-Schnippsel gedacht und werden nicht in die Sprache des Kunden übersetzt!",
        "phone": "Telefonnummer",
        "manager": "Hausverwaltung",
        "owner": "Eigentümer",
        "calendars": {
          "label": "Externe Kalender",
          "url": "URL",
          "url_hint": "http:// oder https:// URL zu iCal-Daten, für extern definierte Termin-Blockings",
          "name": "Name",
          "name_hint": "Name oder kurzer Kommentar (taucht in E-Mails auf)",
          "empty": "Keine externen Kalender definiert.",
          "add": "Kalender hinzufügen",
          "delete": "löschen",
          "keep": "behalten"
        },
        "address": {
          "label": "Adresse",
          "show_in_gmaps": "in Google-Maps anzeigen",
          "street": "Straße",
          "city": "Ort",
          "pcode": "Postleitzahl",
          "region": "Region",
          "country": "Land",
          "unexpected_country": "unerwarteter Länder-Code (erlaubte Werte: %{allowed})",
          "search": "Adresse suchen",
          "search_btn": "Suchen",
          "cancel_btn": "Abbrechen"
        }
      }
    },
    "category_multiple_types": {
      "duschbad": "Duschbad",
      "dusche": "Dusche",
      "einzimmerwohnung": "Einzimmerwohnung",
      "gaestewc": "Gäste-WC",
      "schlafzimmer": "Schlafzimmer",
      "sonstiges": "Sonstiges",
      "vollbad": "Vollbad"
    },
    "admin": {
      "my_booking_pal": {
        "update_progress": {
          "steps": {
            "start": "Basisdaten",
            "images": "Bilder",
            "fees_taxes": "Gebühren und Steuern",
            "los_prices": "Preise"
          }
        }
      },
      "villa_check": {
        "success": "OK",
        "failure": "Fehler",
        "skipped": "Nicht geprüft",
        "checks": {
          "people_prices": {
            "title": "Villa hat Personen-Preise",
            "description": "Bitte Preise hinzufügen (Villa → Bearbeiten → Preise)."
          },
          "has_description": {
            "title": "Villa hat eine Beschreibung",
            "description": "Wenigstens eine englischsprachige Beschreibung ist erforderlich (Villa → Bearbeiten\n→ Merkmale → Beschreibung).\n"
          },
          "clean_description": {
            "title": "Beschreibung ist \"sauber\"",
            "description": "Die Beschreibungstexte dürfen keine Preise, Steuern, Reinigungskosten, Kaution, etc.\nbeschreiben (Villa → Bearbeiten → Merkmale → Beschreibung).\n"
          },
          "key_collection_placeholder": {
            "title": "Safe-Code ist bei Schlüsselübergabe hinterlegt",
            "description": "Der Platzhaltertext ist noch in der Beschreibung enthalten (Villa → Bearbeiten → Weitere\nEigenschaften → Key collection → How should keys be collected?)\n"
          },
          "tags": {
            "title": "Villa ist mit Merkmalen gekennzeichnet, die MyBookingPal bekannt sind.",
            "description": "Unter Villa → Bearbeiten → Merkmale müssen Merkmale ausgewählt sein, die mit\nMyBookingPal verknüpft sind. Unter Objekte → Tags finden sich solche, die in der Spalte\n\"Amenty-IDs\" einen Wert eingetragen haben.\n"
          },
          "has_bedroom": {
            "title": "Villa hat wenigstens ein Badezimmer",
            "description": "Bitte Badezimmer hinzufügen (Villa → Bearbeiten → Merkmale → Badezimmer)"
          },
          "has_bathroom": {
            "title": "Villa hat wenigstens ein Schlafzimmer",
            "description": "Bitte Schlafzimmer hinzufügen (Villa → Bearbeiten → Merkmale → Schlafzimmer)"
          },
          "has_image": {
            "title": "Villa hat Bilder",
            "description": "Unter Villa → Bearbeiten → Fotos wenigstens ein aktives Bild hinzufügen."
          }
        }
      }
    }
  },
  "en": {
    "generic": {
      "add": "add",
      "delete": "delete",
      "remove": "remove",
      "save": "save",
      "cancel": "cancel",
      "please_select": "Please select"
    },
    "error_wrapper": {
      "required": "is required",
      "required_selection": "must be selected",
      "must_not_be_occupied": "already occupied",
      "must_match_category": "doesn't match price category"
    },
    "inquiry_editor": {
      "cancellation": {
        "heading": "Create cancellation for booking/inquiry",
        "create": "Create cancellation",
        "error": "Cancallation could not be saved.",
        "unknown_error": "Unknown error",
        "success": "Successfully cancelled booking/inquiry %{number}",
        "goto": {
          "index": "Go back to list",
          "cancellation": "Show cancellation"
        },
        "reason": "Cancellation reason",
        "reason_hint": "Please provide a (short) reason for this cancellation. This reason is forwarded to the owner and property manger of the villa (and boot, if booked)."
      },
      "uncancellation": {
        "heading": "Undo cancellation",
        "description": "We'll try to restore a booking from this cancellation, but it is possible that the date range now collides with another booking. If this happens, you need to resolve this conflict manually, either by changing the date range or by selecting another villa/boat.",
        "create": "Restore booking",
        "error": "Failed to restore booking.",
        "unknown_error": "Unknown error",
        "success": "Successfully restored booking %{number}",
        "goto": {
          "index": "Go back to list",
          "booking": "Show booking"
        }
      },
      "note_mail": {
        "heading": "Note: Some changes will trigger notification mails for property owners and managers. These emails will be sent automatically:",
        "skip": "This time, skip sending notifications.",
        "villa": {
          "id": "Villa has changed. Owners/managers of the previously selected villa will receive a cancellation, and owners/managers of newly selected villa will reiceice a booking confirmation.",
          "dates": "Travel dates for the villa have changed."
        },
        "boat": {
          "added": "A new boat was added. Owners/managers will receive a booking confirmation.",
          "removed": "The boat was removed. Owners/managers will reiceive a cancellation.",
          "id": "Boat has changed. Owners/managers of the previously selected boat will receive a cancellation, and owners/managers of newly selected boat will reiceice a booking confirmation.",
          "dates": "Lease term for the boat has changed."
        }
      },
      "inquiry": {
        "objects": "Objects",
        "range": "Dates",
        "remote_data": {
          "loading": "Loading booking data…",
          "load_error": "Error loading booking data."
        },
        "villa": {
          "label": "Villa",
          "prices_info": [
            "EUR (+ USD) = prices defined in EUR, autom. conversion for USD",
            "EUR + USD = prices defined in EUR und USD",
            "USD-only = only USD prices available"
          ],
          "villa_missing": "please select a villa"
        },
        "boat": {
          "label": "Boat",
          "loading": null,
          "inclusive": "Boat is included, cannot be changed",
          "add": "Add Boat",
          "remove": "Remove Boat from booking",
          "groups": {
            "optional": "Boats associated with villa",
            "others": "Other boats",
            "inclusive": "Included boat",
            "hidden": "Former boats from existing bookings"
          },
          "invalid": "The boat is not available in the selected date range"
        },
        "incomplete": "You need to select villa and date range, before you can add travelers.",
        "no_enough_travelers": "You need to add at least two adult travelers.",
        "saving_failed": "Saving failed",
        "saving_not_possible": "saving not possible",
        "saving": "Saving",
        "save": "Save"
      },
      "customer": {
        "label": "Customer",
        "external": "external booking",
        "external_hint": [
          "Mark this as an external booking from a portal like airbnb or VRBO.",
          "For external bookings, we don't send automatic emails."
        ],
        "email": "Email address",
        "phone": "Phone number",
        "locale": {
          "label": "Language",
          "de": "German",
          "en": "English"
        },
        "currency": "Currency",
        "title": {
          "label": "Title",
          "m": "Mr.",
          "f": "Mrs."
        },
        "first_name": "Given name",
        "last_name": "Last name"
      },
      "traveler": {
        "label": "Travelers",
        "add": "Add traveler",
        "keep": "Undo",
        "remove": "Remove",
        "first_name": "Given name",
        "last_name": "Last name",
        "category": "Price category",
        "born_on": "Birthday",
        "age_on_arrival": "Age on arrival date",
        "age": "%{n}yo",
        "categories": {
          "adults": "Adults",
          "children_under_6": "Children up to age 6",
          "children_under_12": "Children up to age 12"
        },
        "category_not_available": {
          "abbr": "n/a",
          "title": "not available: villa uses weekly pricing"
        }
      },
      "sidebar": {
        "label": "Booking details",
        "inquiry": {
          "label": "Inquiry/Offer",
          "created_at": "Created at",
          "updated_at": "Last changed at",
          "booked_at": "Booking confirmed at",
          "cancelled_at": "Cancelled at"
        },
        "traveler": {
          "label": "Travelers",
          "unknown": "unknown",
          "born": "born",
          "birthday": "birthday falls in travel period"
        },
        "travel_insurance": {
          "label": "Travel Insurance",
          "unknown": "unknown",
          "insured": "present",
          "not_insured": "not present"
        },
        "bookable": {
          "villa": "Villa",
          "boat": "Boat",
          "dates": "Dates",
          "discounts": "Discounts and surcharges"
        },
        "discounts": {
          "label": "Edit discount/surcharge",
          "category": "Category",
          "dates": "Date range",
          "apply_booking_dates": "Apply travel period",
          "apply_dates": "apply",
          "discount": "Surcharge",
          "discount_hint": "Negative values for discounts, positive values for surcharges, 0 to remove",
          "reload_hint": "After saving, the price table will reload automatically.",
          "high_season_dates": "Dates",
          "high_season_loading": "Loading…",
          "high_season_not_found": "No high season found for the given travel dates.",
          "high_season_overlap": "Overlap",
          "high_season": "High Season"
        }
      },
      "checked_discounts": "Villa or travel dates have changed. Discounts/surcharges are still correct.",
      "common": {
        "local_validation_failed": "local validation failed",
        "remote_validation_failed": "server validation failed",
        "saved_successfully": "Booking data saved successfully",
        "no_server_response": "No response from server"
      },
      "energy_cost": {
        "label": "Energy Cost Calculation",
        "options": {
          "defer": "defer to billing",
          "usage": "by usage",
          "flat": "flat price",
          "included": "included in rent"
        },
        "preset": "villa preset",
        "override": "override value",
        "legacy": "legacy booking"
      }
    },
    "villa_editor": {
      "save_btn": "Save",
      "cancel_btn": "Discard changes",
      "nav": {
        "villa": {
          "label": "Villa Details",
          "section_alias": "Details"
        },
        "tags": {
          "label": "Tags"
        },
        "additional_props": {
          "label": "Additional Properties"
        },
        "prices": {
          "label": "Prices"
        },
        "images": {
          "label": "Pictures",
          "section_alias": "Media"
        },
        "tours": {
          "label": "Tours",
          "section_alias": "Media"
        },
        "pannellums": {
          "label": "Panoramas",
          "section_alias": "Media"
        },
        "videos": {
          "label": "Videos"
        },
        "boats": {
          "label": "Boats"
        },
        "reviews": {
          "label": "Reviews"
        },
        "show": {
          "label": "Show Villa"
        },
        "index": {
          "label": "Back to Villa Listing"
        }
      },
      "section_heading": {
        "edit": "Edit %{label}",
        "create": "Create %{label}"
      },
      "details": {
        "status": "Status",
        "active": "active?",
        "buyable": "for sale?",
        "routing": {
          "label": "Routing",
          "desc": "On which domains is this villa listed?"
        },
        "name": "Name",
        "area": "Living area",
        "pool_orientation": "Pool orientation",
        "build_year": "Year of construction",
        "last_renovation": "Last remodeling",
        "safe_code": "Safe Code",
        "safe_code_hint": "Safe Code and phone number will be included in the traval mail two weeks prior to booking start. These input fields are not supposed to contain arbitrary text snippets and WILL NOT be translated into the customer's language.",
        "phone": "Phone number",
        "manager": "Property management",
        "owner": "Owner",
        "calendars": {
          "label": "External calendars",
          "url": "URL",
          "url_hint": "http:// or https:// URL to iCal files, for externally defined blockings",
          "name": "Name",
          "name_hint": "Name or short comment (is included in emails)",
          "empty": "No external calendar found.",
          "add": "Add calendar",
          "delete": "delete",
          "keep": "keep"
        },
        "address": {
          "label": "Address",
          "show_in_gmaps": "show in Google-Maps",
          "street": "Street",
          "city": "City",
          "pcode": "Zip code",
          "region": "Region",
          "country": "Country",
          "unexpected_country": "unexpected Coundry code (allowed values: %{allowed})",
          "search": "Search addresse",
          "search_btn": "Search",
          "cancel_btn": "Cancel"
        }
      }
    },
    "category_multiple_types": {
      "duschbad": "Shower",
      "dusche": "Shower",
      "einzimmerwohnung": "Studio",
      "gaestewc": "Guest toilet",
      "schlafzimmer": "Bedroom",
      "sonstiges": "Other",
      "vollbad": "Bath"
    },
    "admin": {
      "my_booking_pal": {
        "update_progress": {
          "steps": {
            "start": "product data",
            "images": "images",
            "fees_taxes": "fees and taxes",
            "los_prices": "prices"
          }
        }
      },
      "villa_check": {
        "success": "success",
        "failure": "failure",
        "skipped": "not checked",
        "checks": {
          "people_prices": {
            "title": "Villa has people prices",
            "description": "Go to Villa → Edit → Prices and add prices."
          },
          "has_description": {
            "title": "Villa has a description",
            "description": "Go to Villa → Edit → Tags and add at least the english description text."
          },
          "clean_description": {
            "title": "Villa has a clean description",
            "description": "Go to Villa → Edit → Tags and remove any mention of prices, taxes, deposit, cleaning,\netc. from the description text.\n"
          },
          "key_collection_placeholder": {
            "title": "Key collection contains safe code",
            "description": "The placeholder text is still present (Villa → Edit → Additional Properties → Key\ncollection → How should keys be collected?)\n"
          },
          "tags": {
            "title": "Villa has tags known to MyBookingPal",
            "description": "Go to Villa → Edit → Tags and select tags related to MyBookingPal. Go to Objects →\nTags to find tags with \"Amenity ID\"\n"
          },
          "has_bedroom": {
            "title": "Villa has at least one bedroom",
            "description": "Go to Villa → Edit → Tags → Bedrooms and add a bedroom."
          },
          "has_bathroom": {
            "title": "Villa has at least one bathroom",
            "description": "Go to Villa → Edit → Tags → Bathrooms and add a bathroom."
          },
          "has_image": {
            "title": "Villa has at least one image",
            "description": "Go to Villa → Edit → Pictures and add or activate at least one image."
          }
        }
      }
    }
  }
}
