## Rails cops - https://docs.rubocop.org/rubocop-capybara/cops_rspec.html

require:
  - rubocop-capybara

Capybara:
  Enabled: true

Capybara/MatchStyle: # new in <<next>>
  Enabled: true

Capybara/SpecificMatcher: # new in 2.12
  Enabled: true

Capybara/NegationMatcher: # new in 2.14
  Enabled: true

Capybara/SpecificActions: # new in 2.14
  Enabled: true

Capybara/SpecificFinders: # new in 2.13
  Enabled: true

Capybara/ClickLinkOrButtonStyle: # new in 2.19
  Enabled: true
  EnforcedStyle: link_or_button # default: strict

Capybara/RSpec/HaveSelector: # new in 2.19
  Enabled: true

Capybara/RSpec/PredicateMatcher: # new in 2.19
  Enabled: true

Capybara/RedundantWithinFind: # new in 2.20
  Enabled: true
