# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks
base_locale: de
locales: [de, en]
# internal_locale: en

data:
  # adapter: I18n::Tasks::Data::FileSystem
  # router: convervative_router

  read:
    ## Default:
    #- config/locales/%{locale}.yml
    ## More files:
    - config/locales/**/*.%{locale}.yml
    - config/locales/%{locale}/**/*.yml
    ## Another gem (replace %#= with %=):
    # - "<%#= %x[bundle show vagrant].chomp %>/templates/locales/%{locale}.yml"

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - - '{admin,billings,devise,formtastic,js,countries,settings,shared,villas,recaptcha}.*'
      - 'config/locales/%{locale}/\1.yml'
    - ['{activemodel,activerecord}.*',                  'config/locales/%{locale}/models.yml']
    - ['{errors,date,datetime,number,time,support}.*',  'config/locales/%{locale}/rails.yml']
    - ['{category,tags}.*',                             'config/locales/%{locale}/tags.yml']
    - ['*_mailer.*',                                    'config/locales/%{locale}/mailers.yml']
    # Catch-all default:
    - config/locales/application.%{locale}.yml

  yaml:
    write:
      line_width: 120

search:
  ## Paths or `File.find` patterns to search in:
  # paths:
  #  - app/

  ## Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/views
    - app/boat_views

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - app/assets/images
    - app/assets/fonts
    - "*.swf"
    - "**/node_modules/**"
    - "*.vue"
    - "*.js"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # include: ["*.rb", "*.html.slim"]

  ## Default scanner finds t() and I18n.t() calls.
  # scanner: I18n::Tasks::Scanners::PatternWithScopeScanner

## Do not consider these keys missing:
# ignore_missing:
# - 'errors.messages.{accepted,blank,invalid,too_short,too_long}'
# - '{devise,simple_form}.*'

## Consider these keys used:
ignore_unused:
- '{activemodel,activerecord}.attributes.*'
- '{errors,date,datetime,number,time}.*'
- '{devise,will_paginate,formtastic}.*'
- 'countries.*'
- 'booking_mailer.*'
- '{js,tags}.*'

## Exclude these keys from the `i18n-tasks eq-base' report:
# ignore_eq_base:
#   all:
#     - common.ok
#   fr,es:
#     - common.brand

## Ignore these keys completely:
# ignore:
#  - kaminari.*
