/** @file Generated by `rake js:i18n:frontend` - DO NOT EDIT */

export default {
  "de": {
    "boat_booking": {
      "show_boats": "Boote anzeigen",
      "remove_boat": "Boot entfernen",
      "continue_without_boat": "Weiter ohne Boot",
      "no_boats_available": "Keine passenden Boote gefunden.",
      "modal": {
        "select": "Boot auswählen",
        "cancel": "Abbrechen",
        "prev_boat": "vorheriges Boot",
        "next_boat": "nächstes Boot"
      },
      "details": {
        "description": "Beschreibung",
        "hp": "Leistung",
        "hp_value": "%{ps} PS",
        "video": "Video",
        "training": "Anlieferung und Einweisung",
        "deposit": "Kaution",
        "discount": {
          "name_amount": "%{discount}: %{percent}% Aufschlag",
          "range": "(%{days_before} Tage vorher bis %{days_after} Tage nachher)"
        },
        "availability": "Verfügbarkeit"
      },
      "availability": {
        "full": {
          "title": "Keine Einschränkungen",
          "desc": "Dieses Boot steht im gesamten Reisezeitraum zur Verfügung."
        },
        "limited": {
          "title": "Eingeschränkte Verfügbarkeit",
          "desc": "Dieses Boot steht nicht im gesamten Reisezeitraum zur Verfügung."
        },
        "none": {
          "title": "Derzeit leider nicht verfügbar",
          "desc": "Dieses Boot ist bereits vermietet."
        }
      },
      "prices": {
        "title": "Preise",
        "per_day": "Preis/Tag",
        "period": "Mietdauer",
        "starting_from": "ab",
        "total": "Total",
        "days": {
          "max": {
            "one": "1 Tag und länger",
            "other": "%{count} Tage und länger"
          },
          "min": {
            "one": "1 Tag (Mindestmietsdauer)",
            "other": "%{count} Tage (Mindestmietsdauer)"
          },
          "normal": {
            "one": "1 Tag",
            "other": "%{count} Tage"
          }
        }
      }
    },
    "bsp1_form": {
      "cardpan": "Kartennummer",
      "downpayment": "nur Anzahlung (%{sum})",
      "error": "Bei Ihrer Zahlung ist ein Fehler aufgetreten.",
      "full_payment": "Anzahlung und Restzahlung (%{sum})",
      "pay_now": "Jetzt Bezahlen",
      "success": "Ihre Zahlung wird jetzt bearbeitet. Wenn Ihre Zahlung bei uns eingegangen ist, aktualisiert sich diese Seite automatisch und zusätzlich erhalten Sie von uns eine E-Mail.",
      "valid": "gültig bis (mm/jjjj)"
    },
    "contact_form": {
      "heading": "Nachricht senden",
      "submit": "senden",
      "created": {
        "heading": "Vielen Dank für Ihre Anfrage!",
        "body": "Wir werden uns umgehend um Ihr Anliegen kümmern. Sie erhalten raschmöglichst eine Antwort von uns.",
        "closing": "Freundliche Grüße"
      },
      "request": {
        "email": "E-Mail",
        "name": "Ihr Name",
        "phone": "Telefonnummer",
        "text": "Ihre Nachricht"
      }
    },
    "drp": {
      "btn": {
        "change": "ändern"
      },
      "caption": {
        "high_season": "Hochsaison",
        "today": "heutiges Datum"
      },
      "label": {
        "arrival": "Anreise",
        "departure": "Abreise",
        "please_select": "Bitte wählen",
        "range": "Reisezeitraum",
        "rental_period": "Mietzeitraum"
      },
      "msg": {
        "fill_in": "Der Zeitraum %{start} bis %{end} kann nur im Ganzen gebucht werden.",
        "min_range": "Die Mindestbuchungsdauer beträgt %{min}&nbsp;%{type}."
      },
      "boat": {
        "boat_missing": "bitte ein Boot wählen",
        "aleady_booked": "das gewählte Boot ist im gesamten Zeitraum belegt",
        "dates_missing": "bitte einen Zeitraum auswählen"
      }
    },
    "facets": {
      "apply_filter": "Suche eingrenzen",
      "hide_filters": "weniger Filter",
      "load_message": "Der Filter wird geladen, bitte warten.",
      "more_filters": "mehr Filter",
      "people": "Personen",
      "reset_filter": "zurücksetzen",
      "result_summary": "%{start} bis %{end}, %{people} Pers., %{rooms} Z., %{tags}",
      "results": {
        "one": "Eine Villa zur Ihrer Suchanfrage gefunden",
        "other": "%{count} Villen zu Ihrer Suchanfrage gefunden",
        "zero": "Für diese Suchanfrage haben wir leider keine Villen gefunden"
      },
      "rooms": "Schlafzimmer",
      "search": "Suchen",
      "title": "Finden Sie Ihre Traumvilla"
    },
    "footer": {
      "chat_with_us": "Chat starten",
      "closing": "Ihr Team von Intervilla"
    },
    "header_search": {
      "menu": "Villa suchen",
      "placeholder": "Nach Villaname suchen"
    },
    "infinite_loading": {
      "no_more": "Keine weiteren Bewertungen vorhanden",
      "no_results": "Keine Bewertungen vorhanden",
      "error": "Es ist ein Fehler aufgetreten"
    },
    "maps": {
      "zoom_in": "vergrößern",
      "show_surrounding": "Umgebung anzeigen",
      "more": "Details anzeigen"
    },
    "newsletter": {
      "signup_button": {
        "title": "Zum Newsletter anmelden"
      },
      "signup_modal": {
        "title": "Zum Newsletter anmelden"
      },
      "signup_form": {
        "email": "E-Mail-Adresse",
        "firstname": "Vorname",
        "lastname": "Nachname",
        "subscribe": "Anmelden"
      }
    },
    "price_table": {
      "apply_normal_price": "Normalpreis von %{price} übernehmen",
      "add_clearing_item": "Posten hinzufügen",
      "category": "Kategorie",
      "categories": {
        "handling": "Bearbeitungsgebühr",
        "discount": "Haus-Rabatt",
        "intervillas_discount": "Intervilla-Rabatt",
        "travel_agency_discount": "Reisebüro-Provision",
        "repeater_discount": "Repeater-Rabatt",
        "boat_discount": "Boot-Rabatt",
        "reversal": "Haus-Stornogebühr",
        "boat_reversal": "Boot-Stornogebühr",
        "pet_fee": "Pet-Fee",
        "early_checkin": "Frühes Einchecken",
        "late_checkout": "Spätes Auschecken"
      },
      "clearing_item": {
        "add_note": "Notiz eingeben",
        "add_note_prompt": "Bitte Notiz eingeben:",
        "remove": "löschen",
        "keep": "behalten"
      },
      "dates": "Zeitraum",
      "days": {
        "one": "Tag",
        "other": "Tage"
      },
      "has_normal_price": "Normalpreis vorhanden",
      "heading": "Preise",
      "nights": {
        "one": "Nacht",
        "other": "Nächte"
      },
      "num_people": "Anz. Personen",
      "price": "Preis",
      "rental_price": "Mietkosten",
      "rental_price_including": "Mietkosten inkl. Kaution",
      "sub_total": "Mietpreis (Zwischensumme)",
      "total": "Summe",
      "traveler_categories": {
        "adults": "Erwachsene",
        "base_rate": "Grundpreis für %{count} Pers.",
        "additional_adult": "weitere Person(en)",
        "children_under_6": "Kinder bis 6 J.",
        "children_under_12": "Kinder bis 12 J."
      },
      "traveler_discounts": {
        "easter": "Oster-Aufschlag",
        "christmas": "Weihnachts-Aufschlag",
        "high_season": "Hochsaison-Aufschlag",
        "special": "Last-Minute-Rabatt"
      },
      "invalid": "Preisberechnung nicht möglich."
    },
    "reservation_form": {
      "title": "Anfrage/​Belegungsübersicht",
      "labels": {
        "adults": "Anzahl Erwachsene",
        "children_under_12": "Anzahl Kinder bis 12 Jahre",
        "children_under_6": "Anzahl Kinder bis 6 Jahre"
      },
      "hints": {
        "adults": "es stehen insgesamt %{count} Schlafmöglichkeiten zur Verfügung",
        "children_under_12": "Kinder bis zum vollendeten 12. Lebensjahr am Anreisedatum",
        "children_under_6": "Kinder bis zum vollendeten 6. Lebensjahr am Anreisedatum"
      },
      "beds_fully_occupied": "alle Betten belegt",
      "new_inquiry": "unverbindlich anfragen",
      "clearing": {
        "person_prices": "Personenpreise",
        "boat_prices": "Boot",
        "other_prices": "Sonstiges",
        "total_rent": "Mietpreis",
        "plus_deposit": "zzgl. Kaution",
        "plus": "zzgl.",
        "tax_included": "inkl. Steuern",
        "details": {
          "more": "Details anzeigen",
          "less": "weniger Details"
        },
        "surcharges": {
          "high_season": "Aufschlag: Hochsaison",
          "christmas": "Aufschlag: Weihnachten",
          "easter": "Aufschlag: Oster",
          "special": "Rabatt: Last Minute"
        }
      },
      "nights": {
        "one": "1 Nacht",
        "other": "%{count} Nächte"
      },
      "days": {
        "one": "1 Tag",
        "other": "%{count} Tage"
      }
    },
    "villa_booking": {
      "customer_form": {
        "first_name": "Vorname",
        "last_name": "Nachname",
        "address": "Straße",
        "appnr": "Hausnummer",
        "postal_code": "Postleitzahl",
        "city": "Ort",
        "country": "Land",
        "state_code": "Kanton/Bundesland"
      }
    },
    "villas_list": {
      "error": "Es ist ein Fehler beim Laden der Daten aufgetreten."
    },
    "countries": {
      "AC": "Ascension",
      "AD": "Andorra",
      "AE": "Vereinigte Arabische Emirate",
      "AF": "Afghanistan",
      "AG": "Antigua und Barbuda",
      "AI": "Anguilla",
      "AL": "Albanien",
      "AM": "Armenien",
      "AN": "Niederländische Antillen",
      "AO": "Angola",
      "AQ": "Antarktis",
      "AR": "Argentinien",
      "AS": "Amerikanisch-Samoa",
      "AT": "Österreich",
      "AU": "Australien",
      "AW": "Aruba",
      "AX": "Alandinseln",
      "AZ": "Aserbaidschan",
      "BA": "Bosnien und Herzegowina",
      "BB": "Barbados",
      "BD": "Bangladesch",
      "BE": "Belgien",
      "BF": "Burkina Faso",
      "BG": "Bulgarien",
      "BH": "Bahrain",
      "BI": "Burundi",
      "BJ": "Benin",
      "BL": "St. Barthélemy",
      "BM": "Bermuda",
      "BN": "Brunei Darussalam",
      "BO": "Bolivien",
      "BQ": "Plurinationaler Staat Bolivien",
      "BR": "Brasilien",
      "BS": "Bahamas",
      "BT": "Bhutan",
      "BV": "Bouvetinsel",
      "BW": "Botsuana",
      "BY": "Belarus",
      "BZ": "Belize",
      "CA": "Kanada",
      "CC": "Kokosinseln",
      "CD": "Demokratische Republik Kongod",
      "CF": "Zentralafrikanische Republik",
      "CG": "Kongo-Brazzavilled",
      "CH": "Schweiz",
      "CI": "Elfenbeinküste",
      "CK": "Cookinseln",
      "CL": "Chile",
      "CM": "Kamerun",
      "CN": "China",
      "CO": "Kolumbien",
      "CP": "Clipperton-Insel",
      "CR": "Costa Rica",
      "CS": "Serbien und Montenegro",
      "CU": "Kuba",
      "CV": "Kap Verde",
      "CX": "Weihnachtsinsel",
      "CY": "Zypern",
      "CZ": "Tschechische Republik",
      "DE": "Deutschland",
      "DG": "Diego Garcia",
      "DJ": "Dschibuti",
      "DK": "Dänemark",
      "DM": "Dominica",
      "DO": "Dominikanische Republik",
      "DZ": "Algerien",
      "EA": "Ceuta und Melilla",
      "EC": "Ecuador",
      "EE": "Estland",
      "EG": "Ägypten",
      "EH": "Westsahara",
      "ER": "Eritrea",
      "ES": "Spanien",
      "ET": "Äthiopien",
      "FI": "Finnland",
      "FJ": "Fidschi",
      "FK": "Falklandinseln",
      "FM": "Mikronesien",
      "FO": "Färöer",
      "FR": "Frankreich",
      "FX": "Metropolitan-Frankreichd",
      "GA": "Gabun",
      "GB": "Vereinigtes Königreich",
      "GD": "Grenada",
      "GE": "Georgien",
      "GF": "Französisch-Guayana",
      "GG": "Guernsey",
      "GH": "Ghana",
      "GI": "Gibraltar",
      "GL": "Grönland",
      "GM": "Gambia",
      "GN": "Guinea",
      "GP": "Guadeloupe",
      "GQ": "Äquatorialguinea",
      "GR": "Griechenland",
      "GS": "Südgeorgien und die Südlichen Sandwichinseln",
      "GT": "Guatemala",
      "GU": "Guam",
      "GW": "Guinea-Bissau",
      "GY": "Guyana",
      "HK": "Hongkong",
      "HM": "Heard- und McDonald-Inseln",
      "HN": "Honduras",
      "HR": "Kroatien",
      "HT": "Haiti",
      "HU": "Ungarn",
      "IC": "Kanarische Inseln",
      "ID": "Indonesien",
      "IE": "Irland",
      "IL": "Israel",
      "IM": "Isle of Man",
      "IN": "Indien",
      "IO": "Britisches Territorium im Indischen Ozean",
      "IQ": "Irak",
      "IR": "Iran",
      "IS": "Island",
      "IT": "Italien",
      "JE": "Jersey",
      "JM": "Jamaika",
      "JO": "Jordanien",
      "JP": "Japan",
      "KE": "Kenia",
      "KG": "Kirgisistan",
      "KH": "Kambodscha",
      "KI": "Kiribati",
      "KM": "Komoren",
      "KN": "St. Kitts und Nevis",
      "KP": "Demokratische Volksrepublik Korea",
      "KR": "Republik Korea",
      "KW": "Kuwait",
      "KY": "Kaimaninseln",
      "KZ": "Kasachstan",
      "LA": "Laos",
      "LB": "Libanon",
      "LC": "St. Lucia",
      "LI": "Liechtenstein",
      "LK": "Sri Lanka",
      "LR": "Liberia",
      "LS": "Lesotho",
      "LT": "Litauen",
      "LU": "Luxemburg",
      "LV": "Lettland",
      "LY": "Libyen",
      "MA": "Marokko",
      "MC": "Monaco",
      "MD": "Republik Moldau",
      "ME": "Montenegro",
      "MF": "St. Martin",
      "MG": "Madagaskar",
      "MH": "Marshallinseln",
      "MI": "Midwayinseln",
      "MK": "Mazedoniend",
      "ML": "Mali",
      "MM": "Myanmar",
      "MN": "Mongolei",
      "MO": "Macaud",
      "MP": "Nördliche Marianen",
      "MQ": "Martinique",
      "MR": "Mauretanien",
      "MS": "Montserrat",
      "MT": "Malta",
      "MU": "Mauritius",
      "MV": "Malediven",
      "MW": "Malawi",
      "MX": "Mexiko",
      "MY": "Malaysia",
      "MZ": "Mosambik",
      "NA": "Namibia",
      "NC": "Neukaledonien",
      "NE": "Niger",
      "NF": "Norfolkinsel",
      "NG": "Nigeria",
      "NI": "Nicaragua",
      "NL": "Niederlande",
      "NO": "Norwegen",
      "NP": "Nepal",
      "NR": "Nauru",
      "NU": "Niue",
      "NZ": "Neuseeland",
      "OM": "Oman",
      "PA": "Panama",
      "PE": "Peru",
      "PF": "Französisch-Polynesien",
      "PG": "Papua-Neuguinea",
      "PH": "Philippinen",
      "PK": "Pakistan",
      "PL": "Polen",
      "PM": "St. Pierre und Miquelon",
      "PN": "Pitcairn",
      "PR": "Puerto Rico",
      "PS": "Palästinensische Autonomiegebiete",
      "PT": "Portugal",
      "PW": "Palau",
      "PY": "Paraguay",
      "QA": "Katar",
      "QO": "Äußeres Ozeanien",
      "RE": "Réunion",
      "RO": "Rumänien",
      "RS": "Serbien",
      "RU": "Russische Föderation",
      "RW": "Ruanda",
      "SA": "Saudi-Arabien",
      "SB": "Salomonen",
      "SC": "Seychellen",
      "SD": "Sudan",
      "SE": "Schweden",
      "SG": "Singapur",
      "SH": "St. Helena",
      "SI": "Slowenien",
      "SJ": "Svalbard und Jan Mayen",
      "SK": "Slowakei",
      "SL": "Sierra Leone",
      "SM": "San Marino",
      "SN": "Senegal",
      "SO": "Somalia",
      "SR": "Suriname",
      "ST": "São Tomé und Príncipe",
      "SV": "El Salvador",
      "SY": "Syrien",
      "SZ": "Swasiland",
      "TA": "Tristan da Cunha",
      "TC": "Turks- und Caicosinseln",
      "TD": "Tschad",
      "TF": "Französische Süd- und Antarktisgebiete",
      "TG": "Togo",
      "TH": "Thailand",
      "TJ": "Tadschikistan",
      "TK": "Tokelau",
      "TL": "Osttimor",
      "TM": "Turkmenistan",
      "TN": "Tunesien",
      "TO": "Tonga",
      "TR": "Türkei",
      "TT": "Trinidad und Tobago",
      "TV": "Tuvalu",
      "TW": "Taiwan",
      "TZ": "Tansania",
      "UA": "Ukraine",
      "UG": "Uganda",
      "UM": "Amerikanisch-Ozeanien",
      "US": "Vereinigte Staaten",
      "UY": "Uruguay",
      "UZ": "Usbekistan",
      "VA": "Vatikanstadt",
      "VC": "St. Vincent und die Grenadinen",
      "VE": "Venezuela",
      "VG": "Britische Jungferninseln",
      "VI": "Amerikanische Jungferninseln",
      "VN": "Vietnam",
      "VU": "Vanuatu",
      "WF": "Wallis und Futuna",
      "WS": "Samoa",
      "YE": "Jemen",
      "YT": "Mayotte",
      "ZA": "Südafrika",
      "ZM": "Sambia",
      "ZW": "Simbabwe"
    },
    "state_names": {
      "AE": true,
      "AR": true,
      "AT": true,
      "AU": true,
      "BA": true,
      "BE": true,
      "BR": true,
      "ET": true,
      "FM": true,
      "IN": true,
      "IQ": true,
      "KM": true,
      "MX": true,
      "MY": true,
      "NG": true,
      "NP": true,
      "PK": true,
      "SO": true,
      "VE": true,
      "CA": {
        "label": "Provinz/Territorium",
        "AB": "Alberta",
        "BC": "British Columbia",
        "MB": "Manitoba",
        "NL": "Neufundland und Labrador",
        "NB": "New Brunswick",
        "NT": "Nordwest-Territorien",
        "NS": "Nova Scotia",
        "NU": "Nunavut",
        "ON": "Ontario",
        "PE": "Prince Edward Island",
        "QC": "Québec",
        "SK": "Saskatchewan",
        "YT": "Yukon"
      },
      "CH": {
        "label": "Kanton",
        "AG": "Aargau",
        "AI": "Appenzell Innerrhoden",
        "AR": "Appenzell Ausserrhoden",
        "BE": "Bern",
        "BL": "Basel-Landschaft",
        "BS": "Basel-Stadt",
        "FR": "Freiburg",
        "GE": "Genève",
        "GL": "Glarus",
        "GR": "Graubünden",
        "JU": "Jura",
        "LU": "Luzern",
        "NE": "Neuchâtel",
        "NW": "Nidwalden",
        "OW": "Obwalden",
        "SG": "St. Gallen",
        "SH": "Schaffhausen",
        "SO": "Solothurn",
        "SZ": "Schwyz",
        "TG": "Thurgau",
        "TI": "Ticino",
        "UR": "Uri",
        "VD": "Vaud",
        "VS": "Wallis",
        "ZG": "Zug",
        "ZH": "Zürich"
      },
      "DE": {
        "label": "Bundesland",
        "BB": "Brandenburg",
        "BE": "Berlin",
        "BW": "Baden-Württemberg",
        "BY": "Bayern",
        "HB": "Bremen",
        "HE": "Hessen",
        "HH": "Hamburg",
        "MV": "Mecklenburg-Vorpommern",
        "NI": "Niedersachsen",
        "NW": "Nordrhein-Westfalen",
        "RP": "Rheinland-Pfalz",
        "SH": "Schleswig-Holstein",
        "SL": "Saarland",
        "SN": "Sachsen",
        "ST": "Sachsen-Anhalt",
        "TH": "Thüringen"
      },
      "US": {
        "label": "Bundesstaat",
        "AL": "Alabama",
        "AK": "Alaska",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "Kalifornien",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "FL": "Florida",
        "GA": "Georgia",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PA": "Pennsylvania",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming"
      }
    },
    "activerecord": {
      "attributes": {
        "villa": {
          "pool_orientation": "Ausrichtung Pool"
        }
      }
    },
    "area_tags": {
      "badewanne": "Badewanne",
      "doppelbett": "Doppelbett",
      "dusche": "Dusche",
      "einzelbett": "Einzelbett",
      "franzoesischbettgross": "Kingsize (Doppelbett gross)",
      "franzoesischbettklein": "Queensize (Doppelbett normal)",
      "jacuzzi": "Jacuzzi",
      "schlafsofa": "Schlafsofa",
      "wc": "WC"
    },
    "date": {
      "month_names": [
        null,
        "Januar",
        "Februar",
        "März",
        "April",
        "Mai",
        "Juni",
        "Juli",
        "August",
        "September",
        "Oktober",
        "November",
        "Dezember"
      ]
    },
    "home": {
      "dynamic": {
        "slide": {
          "disrupt": {
            "boat_rental": "Boots­ver­mie­tung",
            "goto_boat_rental": "Alle Angebote anzeigen",
            "search_profile": "Suchprofil"
          },
          "view": "Alle Villen auf einen Blick"
        }
      }
    },
    "shared": {
      "discount": {
        "days_count": {
          "one": "1 Tag",
          "other": "%{count} Tage"
        },
        "nights_count": {
          "one": "1 Nacht",
          "other": "%{count} Nächte"
        },
        "range": "%{start} bis %{end}",
        "subjects": {
          "christmas": "Weihnachten",
          "easter": "Ostern",
          "high_season": "Hochsaison",
          "special": "Last Minute"
        },
        "types": {
          "addition": "%{amount}% Aufschlag",
          "discount": "%{amount}% Rabatt"
        },
        "kinds": {
          "addition": {
            "add": "Aufschlag hinzufügen",
            "edit": "Aufschlag bearbeiten"
          },
          "discount": {
            "add": "Rabatt hinzufügen",
            "edit": "Rabatt bearbeiten"
          }
        }
      }
    },
    "villas": {
      "cardinal_directions": {
        "e": "Ost",
        "n": "Nord",
        "ne": "Nord-Ost",
        "nw": "Nord-West",
        "s": "Süden",
        "se": "Süd-Ost",
        "sw": "Süd-West",
        "w": "West"
      }
    }
  },
  "en": {
    "boat_booking": {
      "show_boats": "Show boats",
      "remove_boat": "Remove boat",
      "continue_without_boat": "Continue without boat",
      "no_boats_available": "Sorry, there are currently no boats available.",
      "modal": {
        "select": "Select boat",
        "cancel": "Cancel",
        "prev_boat": "Previous",
        "next_boat": "Next"
      },
      "details": {
        "description": "Description",
        "hp": "Horse power",
        "hp_value": "%{ps} bhp",
        "video": "Video",
        "training": "Delivery and training",
        "deposit": "Deposit",
        "discount": {
          "name_amount": "%{discount}: %{percent}% surcharge",
          "range": "(%{days_before} days ahead to %{days_after} days later)"
        },
        "availability": "Availability"
      },
      "availability": {
        "full": {
          "title": "No limits",
          "desc": "This boat is available for booking."
        },
        "limited": {
          "title": "Limited availability",
          "desc": "This boat is not available for the whole travel period."
        },
        "none": {
          "title": "Currently not available",
          "desc": "Sorry, this boat is currently not available for booking."
        }
      },
      "prices": {
        "title": "Prices",
        "period": "Period",
        "per_day": "Price per day",
        "total": "Total",
        "starting_from": "starting from",
        "days": {
          "max": {
            "one": "1 day and more",
            "other": "%{count} days and more"
          },
          "min": {
            "one": "1 day (min. period)",
            "other": "%{count} days (min. period)"
          },
          "normal": {
            "one": "1 day",
            "other": "%{count} days"
          }
        }
      }
    },
    "bsp1_form": {
      "cardpan": "Card Number",
      "downpayment": "just downpayment (%{sum})",
      "error": "An error has occurred while processing your payment.",
      "full_payment": "both downpayment and remainder (%{sum})",
      "pay_now": "pay now",
      "success": "Your payment is getting processed. You will receive an E-Mail, when we have received your payment.",
      "valid": "valid until (mm/yyyy)"
    },
    "contact_form": {
      "heading": "Send a message",
      "submit": "send",
      "created": {
        "heading": "Thank you for your inquiry!",
        "body": "We will immediately take care of your concerns. You will receive a response from us as soon as possible.",
        "closing": "Sincerely"
      },
      "request": {
        "email": "Your email address",
        "name": "Your name",
        "phone": "Your phone number",
        "text": "Your message"
      }
    },
    "drp": {
      "btn": {
        "change": "change"
      },
      "caption": {
        "high_season": "high season",
        "today": "today's date"
      },
      "label": {
        "arrival": "Arrival",
        "departure": "Departure",
        "please_select": "Please select",
        "range": "Booking period",
        "rental_period": "Rental period"
      },
      "msg": {
        "fill_in": "The range %{start} until %{end} can only be booked en bloc.",
        "min_range": "The minimal booking period is %{min}&nbsp;%{type}."
      },
      "boat": {
        "boat_missing": "please select a boat",
        "aleady_booked": "the boat is not available for the chosen dates",
        "dates_missing": "please select a date range"
      }
    },
    "facets": {
      "apply_filter": "apply filter",
      "hide_filters": "hide filters",
      "load_message": "Loading filter, please wait.",
      "more_filters": "more filters",
      "people": "People",
      "reset_filter": "reset filter",
      "result_summary": "%{start} until %{end}, %{people} ppl., %{rooms} r, %{tags}",
      "results": {
        "one": "Found one villa matching your search criteria",
        "other": "Found %{count} villas matching your search criteria",
        "zero": "Unfortunately, no villa matched your search criteria"
      },
      "rooms": "Bedrooms",
      "search": "search",
      "title": "Find your dream villa"
    },
    "footer": {
      "chat_with_us": "Chat with us",
      "closing": "Your Intervilla Team"
    },
    "header_search": {
      "menu": "Search by Villa name",
      "placeholder": "Search by Villa name"
    },
    "infinite_loading": {
      "no_more": "No more Reviews",
      "no_results": "No Reviews",
      "error": "There was an Error"
    },
    "maps": {
      "zoom_in": "Zoom in",
      "show_surrounding": "Show surrounding",
      "more": "More information"
    },
    "newsletter": {
      "signup_button": {
        "title": "Subscribe to our newsletter"
      },
      "signup_modal": {
        "title": "Subscribe to our newsletter"
      },
      "signup_form": {
        "email": "Email address",
        "firstname": "First name",
        "lastname": "Last name",
        "subscribe": "Subscribe"
      }
    },
    "price_table": {
      "apply_normal_price": "Apply normal price: %{price}",
      "add_clearing_item": "Add clearing item",
      "category": "category",
      "categories": {
        "handling": "Handling fee",
        "discount": "Villa discount",
        "intervillas_discount": "Intervilla discount",
        "travel_agency_discount": "Travel agency provision",
        "repeater_discount": "Repeater discount",
        "boat_discount": "Boot discount",
        "reversal": "Cancelation fee",
        "boat_reversal": "Boot cancelation fee",
        "pet_fee": "Pet fee",
        "early_checkin": "Early check-in",
        "late_checkout": "Late check-out"
      },
      "clearing_item": {
        "add_note": "add note",
        "add_note_prompt": "Please add note:",
        "remove": "remove",
        "keep": "keep"
      },
      "dates": "dates",
      "days": {
        "one": "day",
        "other": "days"
      },
      "has_normal_price": "has normal price",
      "heading": "Prices",
      "nights": {
        "one": "night",
        "other": "nights"
      },
      "num_people": "# pers.",
      "price": "price",
      "rental_price": "Rental price",
      "rental_price_including": "Rental price incl. deposit(s)",
      "sub_total": "Rental price (sub total)",
      "total": "total",
      "traveler_categories": {
        "adults": "adults",
        "base_rate": "base rate for %{count} people",
        "additional_adult": "additional adult(s)",
        "children_under_6": "children up to age 6",
        "children_under_12": "children up to age 12"
      },
      "traveler_discounts": {
        "easter": "Easter surcharge",
        "christmas": "Christmas surcharge",
        "high_season": "Peak season surcharge",
        "special": "Last minute discount"
      },
      "invalid": "Cannot compute prices."
    },
    "reservation_form": {
      "title": "Reservation",
      "labels": {
        "adults": "No. of adults",
        "children_under_12": "No. of children up to age 12",
        "children_under_6": "No. of children up to age 6"
      },
      "hints": {
        "adults": "the villa provides beds for up to %{count} people",
        "children_under_12": "children for whith the 12th birthday falls on the date of arrival (or later)",
        "children_under_6": "children for whith the 6th birthday falls on the date of arrival (or later)"
      },
      "beds_fully_occupied": "all beds fully occupied",
      "new_inquiry": "start booking inquiry",
      "clearing": {
        "person_prices": "Person prices",
        "boat_prices": "Boat",
        "other_prices": "Miscellaneous prices",
        "total_rent": "Total rent",
        "plus_deposit": "plus deposit",
        "plus": "plus",
        "tax_included": "incl. taxes",
        "details": {
          "more": "breakdown price",
          "less": "show summary"
        },
        "surcharges": {
          "high_season": "surcharge: high season",
          "christmas": "surcharge: christmas",
          "easter": "surcharge: easter",
          "special": "discount: last minute"
        }
      },
      "nights": {
        "one": "1 night",
        "other": "%{count} nights"
      },
      "days": {
        "one": "1 day",
        "other": "%{count} days"
      }
    },
    "villa_booking": {
      "customer_form": {
        "first_name": "Given name",
        "last_name": "Last name",
        "address": "Street",
        "appnr": "Number",
        "postal_code": "ZIP",
        "city": "City",
        "country": "Country",
        "state_code": "State/Province"
      }
    },
    "villas_list": {
      "error": "An error occured whilst loading the villa data."
    },
    "countries": {
      "AC": "Ascension",
      "AD": "Andorra",
      "AE": "United Arab Emirates",
      "AF": "Afghanistan",
      "AG": "Antigua and Barbuda",
      "AI": "Anguilla",
      "AL": "Albania",
      "AM": "Armenia",
      "AN": "Netherlands Antilles",
      "AO": "Angola",
      "AQ": "Antarctica",
      "AR": "Argentina",
      "AS": "American Samoa",
      "AT": "Austria",
      "AU": "Australia",
      "AW": "Aruba",
      "AX": "Aland Islands",
      "AZ": "Azerbaijan",
      "BA": "Bosnia and Herzegovina",
      "BB": "Barbados",
      "BD": "Bangladesh",
      "BE": "Belgium",
      "BF": "Burkina Faso",
      "BG": "Bulgaria",
      "BH": "Bahrain",
      "BI": "Burundi",
      "BJ": "Benin",
      "BL": "Saint Barthélemy",
      "BM": "Bermuda",
      "BN": "Brunei",
      "BO": "Bolivia",
      "BQ": "The Plurinational State of Bolivia",
      "BR": "Brazil",
      "BS": "Bahamas",
      "BT": "Bhutan",
      "BV": "Bouvet Island",
      "BW": "Botswana",
      "BY": "Belarus",
      "BZ": "Belize",
      "CA": "Canada",
      "CC": "Cocos Islands",
      "CD": "Congo - Kinshasa",
      "CF": "Central African Republic",
      "CG": "Congo - Brazzaville",
      "CH": "Switzerland",
      "CI": "Ivory Coast",
      "CK": "Cook Islands",
      "CL": "Chile",
      "CM": "Cameroon",
      "CN": "China",
      "CO": "Colombia",
      "CP": "Clipperton Island",
      "CR": "Costa Rica",
      "CS": "Serbia and Montenegro",
      "CU": "Cuba",
      "CV": "Cape Verde",
      "CX": "Christmas Island",
      "CY": "Cyprus",
      "CZ": "Czech Republic",
      "DE": "Germany",
      "DG": "Diego Garcia",
      "DJ": "Djibouti",
      "DK": "Denmark",
      "DM": "Dominica",
      "DO": "Dominican Republic",
      "DZ": "Algeria",
      "EA": "Ceuta and Melilla",
      "EC": "Ecuador",
      "EE": "Estonia",
      "EG": "Egypt",
      "EH": "Western Sahara",
      "ER": "Eritrea",
      "ES": "Spain",
      "ET": "Ethiopia",
      "FI": "Finland",
      "FJ": "Fiji",
      "FK": "Falkland Islands",
      "FM": "Micronesia",
      "FO": "Faroe Islands",
      "FR": "France",
      "FX": "Metropolitan France",
      "GA": "Gabon",
      "GB": "United Kingdom",
      "GD": "Grenada",
      "GE": "Georgia",
      "GF": "French Guiana",
      "GG": "Guernsey",
      "GH": "Ghana",
      "GI": "Gibraltar",
      "GL": "Greenland",
      "GM": "Gambia",
      "GN": "Guinea",
      "GP": "Guadeloupe",
      "GQ": "Equatorial Guinea",
      "GR": "Greece",
      "GS": "South Georgia and the South Sandwich Islands",
      "GT": "Guatemala",
      "GU": "Guam",
      "GW": "Guinea-Bissau",
      "GY": "Guyana",
      "HK": "Hong Kong",
      "HM": "Heard Island and McDonald Islands",
      "HN": "Honduras",
      "HR": "Croatia",
      "HT": "Haiti",
      "HU": "Hungary",
      "IC": "Canary Islands",
      "ID": "Indonesia",
      "IE": "Ireland",
      "IL": "Israel",
      "IM": "Isle of Man",
      "IN": "India",
      "IO": "British Indian Ocean Territory",
      "IQ": "Iraq",
      "IR": "Iran",
      "IS": "Iceland",
      "IT": "Italy",
      "JE": "Jersey",
      "JM": "Jamaica",
      "JO": "Jordan",
      "JP": "Japan",
      "KE": "Kenya",
      "KG": "Kyrgyzstan",
      "KH": "Cambodia",
      "KI": "Kiribati",
      "KM": "Comoros",
      "KN": "Saint Kitts and Nevis",
      "KP": "North Korea",
      "KR": "South Korea",
      "KW": "Kuwait",
      "KY": "Cayman Islands",
      "KZ": "Kazakhstan",
      "LA": "Laos",
      "LB": "Lebanon",
      "LC": "Saint Lucia",
      "LI": "Liechtenstein",
      "LK": "Sri Lanka",
      "LR": "Liberia",
      "LS": "Lesotho",
      "LT": "Lithuania",
      "LU": "Luxembourg",
      "LV": "Latvia",
      "LY": "Libya",
      "MA": "Morocco",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MF": "Saint Martin",
      "MG": "Madagascar",
      "MH": "Marshall Islands",
      "MI": "Midway Islands",
      "MK": "Macedonia",
      "ML": "Mali",
      "MM": "Myanmar",
      "MN": "Mongolia",
      "MO": "Macau",
      "MP": "Northern Mariana Islands",
      "MQ": "Martinique",
      "MR": "Mauritania",
      "MS": "Montserrat",
      "MT": "Malta",
      "MU": "Mauritius",
      "MV": "Maldives",
      "MW": "Malawi",
      "MX": "Mexico",
      "MY": "Malaysia",
      "MZ": "Mozambique",
      "NA": "Namibia",
      "NC": "New Caledonia",
      "NE": "Niger",
      "NF": "Norfolk Island",
      "NG": "Nigeria",
      "NI": "Nicaragua",
      "NL": "Netherlands",
      "NO": "Norway",
      "NP": "Nepal",
      "NR": "Nauru",
      "NU": "Niue",
      "NZ": "New Zealand",
      "OM": "Oman",
      "PA": "Panama",
      "PE": "Peru",
      "PF": "French Polynesia",
      "PG": "Papua New Guinea",
      "PH": "Philippines",
      "PK": "Pakistan",
      "PL": "Poland",
      "PM": "Saint Pierre and Miquelon",
      "PN": "Pitcairn",
      "PR": "Puerto Rico",
      "PS": "Palestinian Territory",
      "PT": "Portugal",
      "PW": "Palau",
      "PY": "Paraguay",
      "QA": "Qatar",
      "QO": "Outlying Oceania",
      "RE": "Reunion",
      "RO": "Romania",
      "RS": "Serbia",
      "RU": "Russia",
      "RW": "Rwanda",
      "SA": "Saudi Arabia",
      "SB": "Solomon Islands",
      "SC": "Seychelles",
      "SD": "Sudan",
      "SE": "Sweden",
      "SG": "Singapore",
      "SH": "Saint Helena",
      "SI": "Slovenia",
      "SJ": "Svalbard and Jan Mayen",
      "SK": "Slovakia",
      "SL": "Sierra Leone",
      "SM": "San Marino",
      "SN": "Senegal",
      "SO": "Somalia",
      "SR": "Suriname",
      "ST": "Sao Tome and Principe",
      "SV": "El Salvador",
      "SY": "Syria",
      "SZ": "Swaziland",
      "TA": "Tristan da Cunha",
      "TC": "Turks and Caicos Islands",
      "TD": "Chad",
      "TF": "French Southern Territories",
      "TG": "Togo",
      "TH": "Thailand",
      "TJ": "Tajikistan",
      "TK": "Tokelau",
      "TL": "East Timor",
      "TM": "Turkmenistan",
      "TN": "Tunisia",
      "TO": "Tonga",
      "TR": "Turkey",
      "TT": "Trinidad and Tobago",
      "TV": "Tuvalu",
      "TW": "Taiwan",
      "TZ": "Tanzania",
      "UA": "Ukraine",
      "UG": "Uganda",
      "UM": "United States Minor Outlying Islands",
      "US": "United States",
      "UY": "Uruguay",
      "UZ": "Uzbekistan",
      "VA": "Vatican",
      "VC": "Saint Vincent and the Grenadines",
      "VE": "Venezuela",
      "VG": "British Virgin Islands",
      "VI": "U.S. Virgin Islands",
      "VN": "Vietnam",
      "VU": "Vanuatu",
      "WF": "Wallis and Futuna",
      "WS": "Samoa",
      "YE": "Yemen",
      "YT": "Mayotte",
      "ZA": "South Africa",
      "ZM": "Zambia",
      "ZW": "Zimbabwe"
    },
    "state_names": {
      "AE": true,
      "AR": true,
      "AT": true,
      "AU": true,
      "BA": true,
      "BE": true,
      "BR": true,
      "ET": true,
      "FM": true,
      "IN": true,
      "IQ": true,
      "KM": true,
      "MX": true,
      "MY": true,
      "NG": true,
      "NP": true,
      "PK": true,
      "SO": true,
      "VE": true,
      "CA": {
        "label": "Province/Territory",
        "AB": "Alberta",
        "BC": "British Columbia",
        "MB": "Manitoba",
        "NL": "Newfoundland and Labrador",
        "NB": "New Brunswick",
        "NT": "Northwest Territories",
        "NS": "Nova Scotia",
        "NU": "Nunavut",
        "ON": "Ontario",
        "PE": "Prince Edward Island",
        "QC": "Quebec",
        "SK": "Saskatchewan",
        "YT": "Yukon"
      },
      "CH": {
        "label": "Canton",
        "AG": "Aargau",
        "AI": "Appenzell Inner-Rhodes",
        "AR": "Appenzell Outer-Rhodes",
        "BE": "Bern",
        "BL": "Basel-Country",
        "BS": "Basel-City",
        "FR": "Freiburg",
        "GE": "Geneva",
        "GL": "Glarus",
        "GR": "Grisons",
        "JU": "Jura",
        "LU": "Lucerne",
        "NE": "Neuchâtel",
        "NW": "Nidwald",
        "OW": "Obwald",
        "SG": "St. Gall",
        "SH": "Schaffhouse",
        "SO": "Soleure",
        "SZ": "Schwyz",
        "TG": "Thurgovia",
        "TI": "Tessin",
        "UR": "Uri",
        "VD": "Vaud",
        "VS": "Valais",
        "ZG": "Zug",
        "ZH": "Zurich"
      },
      "DE": {
        "label": "State",
        "BB": "Brandenburg",
        "BE": "Berlin",
        "BW": "Baden-Württemberg",
        "BY": "Bavaria",
        "HB": "Bremen",
        "HE": "Hesse",
        "HH": "Hamburg",
        "MV": "Mecklenburg-Western Pomerania",
        "NI": "Lower Saxony",
        "NW": "North Rhine-Westphalia",
        "RP": "Rhineland-Palatinate",
        "SH": "Schleswig-Holstein",
        "SL": "Saarland",
        "SN": "Saxony",
        "ST": "Saxony-Anhalt",
        "TH": "Thuringia"
      },
      "US": {
        "label": "State",
        "AL": "Alabama",
        "AK": "Alaska",
        "AZ": "Arizona",
        "AR": "Arkansas",
        "CA": "California",
        "CO": "Colorado",
        "CT": "Connecticut",
        "DE": "Delaware",
        "FL": "Florida",
        "GA": "Georgia",
        "HI": "Hawaii",
        "ID": "Idaho",
        "IL": "Illinois",
        "IN": "Indiana",
        "IA": "Iowa",
        "KS": "Kansas",
        "KY": "Kentucky",
        "LA": "Louisiana",
        "ME": "Maine",
        "MD": "Maryland",
        "MA": "Massachusetts",
        "MI": "Michigan",
        "MN": "Minnesota",
        "MS": "Mississippi",
        "MO": "Missouri",
        "MT": "Montana",
        "NE": "Nebraska",
        "NV": "Nevada",
        "NH": "New Hampshire",
        "NJ": "New Jersey",
        "NM": "New Mexico",
        "NY": "New York",
        "NC": "North Carolina",
        "ND": "North Dakota",
        "OH": "Ohio",
        "OK": "Oklahoma",
        "OR": "Oregon",
        "PA": "Pennsylvania",
        "RI": "Rhode Island",
        "SC": "South Carolina",
        "SD": "South Dakota",
        "TN": "Tennessee",
        "TX": "Texas",
        "UT": "Utah",
        "VT": "Vermont",
        "VA": "Virginia",
        "WA": "Washington",
        "WV": "West Virginia",
        "WI": "Wisconsin",
        "WY": "Wyoming"
      }
    },
    "activerecord": {
      "attributes": {
        "villa": {
          "pool_orientation": "Orientation of pool"
        }
      }
    },
    "area_tags": {
      "badewanne": "Bath",
      "doppelbett": "Double bed",
      "dusche": "Shower",
      "einzelbett": "Single bed",
      "franzoesischbettgross": "King size (double size)",
      "franzoesischbettklein": "Queen size (normal size)",
      "jacuzzi": "Jacuzzi",
      "schlafsofa": "Sleeper sofa",
      "wc": "Toilet"
    },
    "date": {
      "month_names": [
        null,
        "January",
        "February",
        "March",
        "April",
        "May",
        "June",
        "July",
        "August",
        "September",
        "October",
        "November",
        "December"
      ]
    },
    "home": {
      "dynamic": {
        "slide": {
          "disrupt": {
            "boat_rental": "Boat rental",
            "goto_boat_rental": "Show current selection",
            "search_profile": "Seach profile"
          },
          "view": "Discover holiday home"
        }
      }
    },
    "shared": {
      "discount": {
        "days_count": {
          "one": "1 day",
          "other": "%{count} days"
        },
        "nights_count": {
          "one": "1 night",
          "other": "%{count} nights"
        },
        "range": "%{start} until %{end}",
        "subjects": {
          "christmas": "Christmas",
          "easter": "Easter",
          "high_season": "High Season",
          "special": "Last Minute"
        },
        "types": {
          "addition": "%{amount}% surcharge",
          "discount": "%{amount}% discount"
        },
        "kinds": {
          "addition": {
            "add": "add surcharge",
            "edit": "edit surcharge"
          },
          "discount": {
            "add": "add discount",
            "edit": "edit discount"
          }
        }
      }
    },
    "villas": {
      "cardinal_directions": {
        "e": "east",
        "n": "north",
        "ne": "north east",
        "nw": "north west",
        "s": "south",
        "se": "south east",
        "sw": "south west",
        "w": "west"
      }
    }
  }
}
