/** @file Auto-generated via `rake my_booking_pal:amenities` - DO NOT EDIT */

class Amenity {
  constructor(public id: string, public name: string, public category: string) {}
}
class ResortAmenity extends Amenity {}
class RoomAmenity extends Amenity {}

type AmenityByCategory = Map<string, Map<string, Amenity>>

/** Amenities for the whole resort */
export const RESORT_AMENITIES: AmenityByCategory = new Map()

/** Amenities for the room */
export const ROOM_AMENITIES: AmenityByCategory = new Map()

// MyBookingPal has distinct amenities for the resort and the room (think: hotel
// vs. room). This doesn't make much sense for Intervillas. We're partitioning
// them nonetheless
;(<[category: string, [resort: boolean, id: string, name: string][]][]>[
  ["Accessibility", [
    [true, "HAC6056", "Accessible Parking: Indoor"],
    [true, "HAC6057", "Accessible Parking: Indoor, 1 spot"],
    [true, "HAC6058", "Accessible Parking: Indoor, 2 spots"],
    [true, "HAC6059", "Accessible Parking: Outdoor"],
    [true, "HAC6060", "Accessible Parking: Outdoor, 1 spot"],
    [true, "HAC6061", "Accessible Parking: Outdoor, 2 spots"],
    [false, "RMA5189", "Accessible by Lift"],
    [false, "RMA6108", "Accessible height bed"],
    [false, "RMA6111", "Accessible height toilet"],
    [true, "HAC116", "Accessible parking"],
    [false, "RMA161", "Accessible room"],
    [false, "RMA5148", "Adapted bath"],
    [false, "RMA1", "Adjoining rooms"],
    [true, "HAC5131", "Auditory Guidance"],
    [true, "HAC5065", "Baby safety gates"],
    [false, "RMA5153", "Bathroom emergency pull cord"],
    [true, "HAC5128", "Bathroom emergency pull cord"],
    [false, "RMA6109", "Bathroom step free access"],
    [false, "RMA6113", "Bathroom wide doorway"],
    [false, "RMA6105", "Bedroom step free access"],
    [false, "RMA6107", "Bedroom wide doorway"],
    [true, "HAC6146", "Ceiling hoist"],
    [true, "HAC6142", "Common space step free access"],
    [true, "HAC6143", "Common space wide doorway"],
    [true, "HAC254", "Connecting rooms"],
    [false, "RMA22", "Connecting rooms"],
    [true, "HAC6042", "Disabled parking spot"],
    [true, "HAC6141", "Electric profiling bed"],
    [false, "RMA6028", "Entire property on ground floor"],
    [false, "RMA5134", "Entire unit wheelchair accessible"],
    [false, "RMA5087", "Executive Lounge Access"],
    [true, "HAC34", "Executive floor"],
    [true, "HAC6041", "Flat smooth pathway to front door"],
    [false, "RMA6110", "Grab rails in shower"],
    [false, "RMA6116", "Handheld shower hear"],
    [false, "RMA5151", "Higher level toilet"],
    [true, "HAC5126", "Higher level toilet"],
    [true, "HAC6038", "Home step free access"],
    [true, "HAC6040", "Home wide doorway"],
    [false, "RMA5152", "Low bathroom sink"],
    [true, "HAC5127", "Low bathroom sink"],
    [true, "HAC6144", "Mobile hoist"],
    [true, "HAC6039", "Path to entrance lit at night"],
    [true, "HAC6145", "Pool hoist"],
    [false, "RMA6075", "Private entrance"],
    [true, "HAC5124", "Property is wheel chair accessible"],
    [false, "RMA5149", "Roll in shower"],
    [false, "RMA6112", "Rollin shower with bench"],
    [true, "HAC5039", "Rooms/Facilities for Disabled"],
    [false, "RMA5154", "Shower chair"],
    [true, "HAC5074", "Strollers"],
    [false, "RMA5147", "Toilet with grab rails"],
    [true, "HAC5125", "Toilet with grab rails"],
    [false, "RMA6114", "Tub with shower bench"],
    [false, "RMA6062", "Upper Floor Reachable By Stairs Only"],
    [false, "RMA5132", "Upper floor reachable by lift"],
    [true, "HAC5129", "Visual aids: Braille"],
    [true, "HAC5130", "Visual aids: Tactile Signs"],
    [false, "RMA5150", "Walk in shower"],
    [true, "HAC101", "Wheelchair access"],
    [false, "RMA6098", "Wheelchair inaccessible"],
    [false, "RMA6106", "Wide clearance to bed"],
    [false, "RMA6115", "Wide clearance to shower and toilet"],
    [true, "HAC6037", "Wide hallway clearance"],
  ]],
  ["Activities", [
    [true, "HAC5106", "Aerobics"],
    [true, "HAC5105", "Archery"],
    [true, "HAC5031", "Badminton equipment"],
    [true, "RST4", "Basketball court"],
    [true, "RST169", "Bikes Available (Free)"],
    [true, "RST111", "Billiards"],
    [true, "HAC5107", "Bingo"],
    [true, "HAC6020", "Boat"],
    [true, "RST7", "Boating"],
    [true, "RST9", "Bowling alley"],
    [true, "RST149", "Canoeing"],
    [true, "RST13", "Cross country skiing"],
    [true, "HAC5032", "Cycling"],
    [true, "HAC6044", "Cycling Trips"],
    [true, "RST14", "Dart board"],
    [true, "RST160", "Diving"],
    [true, "RST20", "Fishing"],
    [true, "HAC5088", "Fitness classes"],
    [true, "RST25", "Fly fishing"],
    [true, "RST34", "Golf"],
    [true, "HAC236", "Golf Course (within 2 miles)"],
    [true, "RST35", "Gym"],
    [true, "RST60", "Hiking trail"],
    [true, "HAC237", "Horseback riding"],
    [true, "RST105", "Hunting"],
    [true, "RST137", "Ice skating"],
    [true, "RST63", "Jet-ski"],
    [true, "RST65", "Kayaking"],
    [true, "RST67", "Miniature golf"],
    [true, "RST68", "Mountain biking trail"],
    [true, "RST108", "Mountain climbing"],
    [true, "HAC6186", "Mountaineering"],
    [true, "HAC6183", "Outdoor golf"],
    [true, "HAC6187", "Outdoor kayak canoe"],
    [true, "RST179", "Paddle boating"],
    [true, "RST73", "Parasailing"],
    [true, "HAC6028", "Petanque"],
    [true, "RST74", "Playground"],
    [true, "HAC231", "Racquetball"],
    [true, "RST112", "Rock climbing"],
    [true, "RST80", "Sailing"],
    [true, "RST82", "Scuba diving"],
    [true, "HAC5108", "Ski Shuttle"],
    [true, "RST156", "Ski in/out facilities"],
    [true, "HAC5036", "Ski pass vendor"],
    [true, "HAC6008", "Ski rental"],
    [true, "HAC6092", "Ski rental: Available for additional fee"],
    [true, "HAC6093", "Ski rental: Rental cost included with stay"],
    [true, "HAC5034", "Ski school"],
    [true, "RST180", "Sledding"],
    [true, "RST86", "Snorkeling"],
    [true, "RST87", "Snow boarding"],
    [true, "RST120", "Snow mobiling"],
    [true, "HAC272", "Snow skiing"],
    [true, "HAC232", "Snow sports"],
    [true, "RST79", "Sports Whitewater Rafting"],
    [true, "HAC6150", "Sports deepsea fishing"],
    [true, "HAC6151", "Sports fishing bay"],
    [true, "HAC6152", "Sports fishing freshwater"],
    [true, "HAC6153", "Sports fishing surf"],
    [true, "HAC6182", "Sports golf"],
    [true, "HAC6154", "Sports golf optional"],
    [true, "HAC6155", "Sports mountaineering"],
    [true, "HAC6156", "Sports pier fishing"],
    [true, "HAC6188", "Sports rafting"],
    [true, "HAC6158", "Sports ski lift privileges optional"],
    [true, "HAC6159", "Sports spelunking"],
    [true, "RST92", "Squash court"],
    [true, "RST116", "Surfing"],
    [true, "HAC6100", "Table Tennis: Indoor"],
    [true, "HAC6101", "Table Tennis: Outdoor"],
    [true, "RST117", "Table tennis"],
    [true, "HAC233", "Tennis court"],
    [true, "HAC5030", "Tennis equipment"],
    [true, "RST187", "Trampoline"],
    [true, "RST96", "Tubing"],
    [true, "HAC6106", "Water Sports: Available for additional fee"],
    [true, "HAC6105", "Water Sports: Available for rent"],
    [true, "HAC273", "Water skiing"],
    [true, "HAC234", "Water sports"],
    [true, "RST182", "Whale watching"],
    [true, "RST101", "Windsurfing"],
    [true, "HAC5087", "Yoga classes"],
  ]],
  ["Bathroom", [
    [false, "RMA5118", "Additional Bathroom"],
    [false, "RMA5072", "Additional Toilet"],
    [false, "RMA6150", "Amenity combo tub shower"],
    [false, "RMA6151", "Amenity outdoor shower"],
    [false, "RMA6149", "Amenity toilet"],
    [false, "RMA6077", "Baby bath"],
    [false, "RMA5005", "Bath"],
    [false, "RMA10", "Bathrobe"],
    [true, "HAC6096", "Bathroom Amenities: Robe included"],
    [false, "RMA11", "Bathroom amenities"],
    [false, "RMA13", "Bathtub"],
    [false, "RMA127", "Bathtub &whirlpool separate"],
    [false, "RMA14", "Bathtub only"],
    [false, "RMA15", "Bathtub or Shower"],
    [false, "RMA16", "Bidet"],
    [false, "RMA5179", "Body soap"],
    [false, "RMA5178", "Conditioner"],
    [false, "RMA6125", "Ensuite"],
    [false, "RMA6037", "Essentials"],
    [true, "HAC5083", "Foot bath"],
    [false, "RMA5027", "Free Toiletries"],
    [false, "RMA5042", "Guest toilet"],
    [false, "RMA50", "Hairdryer"],
    [false, "RMA242", "Instant hot water"],
    [false, "RMA138", "Marble bathroom"],
    [false, "RMA141", "Oversized bathtub"],
    [false, "RMA80", "Phone in bathroom"],
    [false, "RMA85", "Private bathroom"],
    [true, "HAC5059", "Public bath"],
    [false, "RMA271", "Separate toilet area"],
    [false, "RMA155", "Separate tub and shower"],
    [false, "RMA276", "Separate tub or shower"],
    [false, "RMA5177", "Shampoo"],
    [false, "RMA193", "Shared bathroom"],
    [false, "RMA142", "Shower"],
    [false, "RMA5180", "Shower cap"],
    [false, "RMA97", "Shower only"],
    [false, "RMA5141", "Toilet paper"],
    [false, "RMA5176", "Toothbrush"],
    [false, "RMA57", "Whirpool"],
  ]],
  ["Business Facilities", [
    [true, "HAC6063", "Business Facilities"],
    [true, "HAC228", "Business center"],
    [true, "HAC14", "Business library"],
    [true, "HAC6033", "EV charger"],
    [true, "HAC269", "Meeting rooms"],
  ]],
  ["Cleaning Services", [
    [false, "RMA5116", "Cleaning products"],
    [true, "HAC21", "Coin operated laundry"],
    [true, "HAC6122", "Dry Cleaning: Available for additional fee"],
    [true, "HAC6121", "Dry Cleaning: On request"],
    [true, "HAC96", "Dry cleaning"],
    [true, "HAC176", "Full service housekeeping"],
    [true, "HAC50", "Housekeeping - daily"],
    [true, "HAC51", "Housekeeping - weekly"],
    [true, "HAC6126", "Housekeeping: 2x Daily"],
    [true, "HAC6127", "Housekeeping: Additional Services"],
    [true, "HAC6129", "Housekeeping: Additional services available for extra fee"],
    [true, "HAC6128", "Housekeeping: Additional services available on request"],
    [true, "HAC6073", "Laundry Facilities"],
    [true, "HAC6132", "Laundry Services"],
    [true, "HAC6133", "Laundry Services: Availabe for additional fee"],
    [true, "HAC168", "Onsite laundry"],
    [true, "HAC6055", "Professionally Cleaned"],
    [true, "HAC81", "Shoe shine stand"],
  ]],
  ["Common Areas", [
    [true, "HAC5012", "Designated smoking area"],
    [true, "HAC5041", "Family Rooms"],
    [true, "HAC44", "Game room"],
    [true, "HAC198", "Non-smoking rooms (generic)"],
    [true, "HAC5009", "Shared lounge/TV area"],
  ]],
  ["Entertainment and Family Services", [
    [true, "HAC5057", "Adult only"],
    [true, "HAC6108", "Baby Sitting: Available for additional fee"],
    [true, "HAC6107", "Baby Sitting: On request"],
    [true, "HAC8", "Baby sitting"],
    [true, "HAC5098", "Bike tours"],
    [true, "RST127", "Bird watching"],
    [false, "RMA5143", "Board games/puzzles"],
    [true, "HAC5061", "Board games/puzzles"],
    [false, "RMA5144", "Book/DVD/Music library for children"],
    [true, "HAC5062", "Book/DVD/Music library for children"],
    [true, "HAC16", "Casino"],
    [true, "HAC193", "Children's play area"],
    [true, "HAC6097", "Children’s play area: Indoor"],
    [true, "HAC6098", "Children’s play area: Outdoor"],
    [true, "HAC5102", "Cooking class"],
    [true, "HAC195", "Disco"],
    [true, "RST177", "Eco tourism"],
    [true, "HAC5049", "Entertainment Staff"],
    [true, "HAC6148", "Entertainment foosball"],
    [true, "HAC6149", "Entertainment music library"],
    [true, "RST133", "Gambling"],
    [true, "HAC6027", "Games"],
    [true, "HAC6099", "High Chair"],
    [true, "HAC5045", "Karaoke"],
    [true, "HAC5054", "Kids' club"],
    [true, "HAC5064", "Kids' outdoor play equipment"],
    [true, "HAC6165", "Leisure antiquing"],
    [true, "HAC6166", "Leisure wildlife viewing"],
    [true, "HAC60", "Live entertainment"],
    [true, "HAC5103", "Live music/performance"],
    [true, "HAC5104", "Live sports events (broadcast)"],
    [true, "HAC62", "Nightclub"],
    [true, "HAC5094", "Pub crawls"],
    [true, "HAC5095", "Stand-up comedy"],
    [true, "HAC5101", "Tour or class about local culture"],
    [true, "HAC5097", "Walking tours"],
    [true, "HAC5060", "Water slide"],
  ]],
  ["Food and Drink", [
    [true, "HAC156", "All-inclusive meal plan "],
    [true, "HAC9", "BBQ/Picnic area"],
    [true, "HAC6109", "Bartender"],
    [true, "HAC6111", "Bartender: Available for additional fee"],
    [true, "HAC6110", "Bartender: On request"],
    [true, "HAC5071", "Bottle of water"],
    [false, "RMA6099", "Breakfast booking possible"],
    [true, "HAC173", "Breakfast served in restaurant"],
    [true, "HAC226", "Catering services"],
    [true, "HAC6002", "Chef Services"],
    [true, "HAC6116", "Chef Services: Available for additional fee"],
    [true, "HAC6115", "Chef Services: Included"],
    [true, "HAC6117", "Chef Services: Working schedule"],
    [true, "HAC5073", "Chocolate/Cookies"],
    [false, "RMA19", "Coffee/Tea maker"],
    [true, "HAC159", "Continental breakfast"],
    [true, "HAC6001", "Dinner"],
    [true, "HAC5072", "Fruits"],
    [true, "HAC5067", "Kid meals"],
    [true, "HAC5068", "Kid-friendly buffet"],
    [true, "HAC165", "Lounges/bars"],
    [true, "HAC6000", "Lunch"],
    [true, "HAC6135", "Meal Included: 3 meals/ day"],
    [true, "HAC6136", "Meal Included: Available for additional fee"],
    [true, "HAC6134", "Meal Included: Breakfast"],
    [false, "RMA190", "Meal included - continental breakfast"],
    [false, "RMA191", "Meal included - dinner"],
    [false, "RMA192", "Meal included - lunch"],
    [true, "HAC5047", "Packed Lunches"],
    [true, "HAC76", "Restaurant"],
    [true, "HAC77", "Room service"],
    [true, "HAC342", "Snack bar"],
    [true, "HAC5051", "Special Diet Menus (on request)"],
    [true, "HAC5070", "Wine/Champagne"],
  ]],
  ["Front Desk Services", [
    [true, "HAC1", "24 Hour Reception Desk"],
    [true, "HAC22", "Concierge desk"],
    [true, "HAC196", "Early check-in"],
    [true, "HAC36", "Express check-in"],
    [true, "HAC37", "Express check-out"],
    [true, "HAC5050", "Private Check-in/Check-out"],
  ]],
  ["Media & technology", [
    [false, "RMA5", "AM/FM radio"],
    [false, "RMA3", "Alarm clock"],
    [false, "RMA265", "Bluray player"],
    [false, "RMA129", "CD  player"],
    [false, "RMA158", "CNN available"],
    [false, "RMA18", "Cable television"],
    [true, "HAC5066", "Children television networks"],
    [false, "RMA20", "Color television"],
    [false, "RMA21", "Computer"],
    [false, "RMA163", "DVD player"],
    [false, "RMA38", "Fax machine"],
    [false, "RMA5075", "Flat-screen TV"],
    [false, "RMA5103", "Game Console"],
    [false, "RMA6057", "Game Console - Nintendo Wii"],
    [false, "RMA6055", "Game Console - PS2"],
    [false, "RMA6056", "Game Console - PS3"],
    [false, "RMA6054", "Game Console - Xbox 360"],
    [false, "RMA5174", "Game console - PS4"],
    [false, "RMA5173", "Game console - Wii U"],
    [false, "RMA5172", "Game console - Xbox One"],
    [false, "RMA246", "High Definition (HD) Flat Panel Television - 32 inches or greater"],
    [true, "HAC6070", "Home Theatre System"],
    [false, "RMA63", "Laptop"],
    [false, "RMA139", "List of movie channels available"],
    [false, "RMA259", "Movies"],
    [false, "RMA78", "Pay per view movies on TV"],
    [false, "RMA5007", "Pay-per-view Channels"],
    [false, "RMA227", "Premium movie channels"],
    [false, "RMA5044", "Satellite Channels"],
    [false, "RMA217", "Satellite radio"],
    [false, "RMA210", "Satellite television"],
    [false, "RMA5198", "Smartphone"],
    [false, "RMA104", "Stereo"],
    [false, "RMA5199", "Streaming service (such as Netflix)"],
    [false, "RMA251", "TV"],
    [true, "HAC6103", "Television: Flat screen"],
    [true, "HAC6102", "Television: Plasma"],
    [true, "HAC6104", "Television: Smart"],
    [false, "RMA115", "VCR movies"],
    [false, "RMA254", "Video game player:"],
    [false, "RMA117", "Video games"],
    [false, "RMA218", "Video on demand"],
    [false, "RMA5083", "Wake Up Service"],
    [false, "RMA273", "Widescreen TV"],
    [false, "RMA6040", "iPad"],
    [false, "RMA214", "iPod docking station"],
  ]],
  ["Miscellaneous", [
    [true, "HAC5", "Air conditioning"],
    [false, "RMA6", "Baby listening device"],
    [true, "HAC6181", "Bar"],
    [false, "RMA6071", "Buzzer/wireless intercom"],
    [true, "HAC6029", "Car necessary"],
    [true, "HAC6030", "Car not necessary"],
    [true, "HAC6031", "Car recommended"],
    [true, "HAC6054", "Carbon Monoxide Detector + Smoke Detector"],
    [false, "RMA6067", "Carbon monoxide detector"],
    [true, "HAC5008", "Chapel/shrine"],
    [true, "HAC6035", "Cleaning before checkout"],
    [true, "HAC29", "Door man"],
    [true, "HAC316", "Electric car charging stations"],
    [false, "RMA6018", "Electronic key card access"],
    [true, "HAC33", "Elevators"],
    [false, "RMA6021", "Fire extinguishers"],
    [false, "RMA6068", "First aid kit"],
    [false, "RMA45", "Free local calls"],
    [true, "HAC42", "Free parking"],
    [true, "HAC6177", "Golf"],
    [true, "HAC5100", "Happy hour"],
    [true, "HAC242", "Heated guest rooms"],
    [true, "HAC6179", "Highway"],
    [true, "HAC310", "Hypoallergenic rooms"],
    [true, "HAC53", "Indoor parking"],
    [false, "RMA170", "International calls"],
    [true, "HAC197", "Locker room"],
    [false, "RMA175", "Long distance calls"],
    [true, "HAC6034", "Long term stays allowed"],
    [true, "HAC5085", "Massage chair"],
    [true, "HAC154", "Medical Facilities Service"],
    [false, "RMA5203", "Metal keys access"],
    [true, "HAC5096", "Movie nights"],
    [true, "HAC5155", "No Single-Use Plastics"],
    [true, "HAC5156", "No Single-Use Toiletries"],
    [true, "HAC5013", "Pet basket"],
    [true, "HAC5014", "Pet bowls"],
    [false, "RMA5137", "Private flat in block of flats"],
    [true, "HAC230", "Secured parking"],
    [false, "RMA6117", "Single level home"],
    [true, "HAC6180", "Ski"],
    [true, "HAC5033", "Ski Storage"],
    [true, "RST5028", "Ski-to-door access"],
    [false, "RMA100", "Smoke detectors"],
    [true, "HAC312", "Smoke-free property"],
    [true, "HAC6019", "Soap/Shampoo"],
    [true, "HAC186", "Street side parking"],
    [true, "HAC5099", "Themed dinner nights"],
    [true, "HAC6138", "Valet Parking: Available for additional fee"],
    [true, "HAC6137", "Valet Parking: On request"],
    [true, "HAC97", "Valet parking"],
    [true, "HAC5042", "Viproom facilities"],
    [true, "HAC309", "Welcome gift"],
    [false, "RMA151", "Welcome gift"],
  ]],
  ["Nearby Amenities", [
    [true, "ACC1", "Airport"],
    [true, "RST5", "Beach"],
    [true, "ACC203", "Ferry"],
    [true, "HAC199", "Railway"],
    [true, "ACC65", "Shopping  "],
  ]],
  ["Noise", [
    [true, "HAC6047", "Near a train/subway station"],
    [true, "HAC6048", "Nearby local nightlife"],
    [true, "HAC6049", "Shared residential building"],
  ]],
  ["Outdoor & view", [
    [true, "HAC6147", "Amenities garage"],
    [true, "ACC74", "Bay"],
    [true, "ACC5", "Beach"],
    [true, "HAC6062", "Beach Access"],
    [false, "RMA6012", "Beach view"],
    [true, "HAC239", "Beachfront"],
    [true, "ACC90", "Botanical garden"],
    [true, "ACC73", "Cafebar"],
    [false, "RMA6030", "City view"],
    [true, "HAC25", "Courtyard"],
    [true, "HAC6065", "Courtyard: Private Use"],
    [true, "HAC6064", "Courtyard: Shared"],
    [true, "ACC114", "Duty Free"],
    [true, "HAC6066", "Fire Pit"],
    [true, "RST134", "Garden"],
    [false, "RMA6051", "Garden view"],
    [true, "ACC47", "General supplies"],
    [false, "RMA6027", "Golf view"],
    [false, "RMA220", "Gulf view"],
    [false, "RMA6031", "Harbor view"],
    [true, "ACC24", "Hospital"],
    [true, "HAC5053", "Hot Spring Bath"],
    [false, "RMA5190", "Inner courtyard view"],
    [true, "ACC25", "Lake"],
    [false, "RMA6029", "Lake view"],
    [true, "HAC6072", "Lakefront"],
    [false, "RMA5113", "Landmark View"],
    [true, "ACC27", "Library"],
    [true, "HAC6169", "Location type downtown"],
    [true, "HAC6168", "Location type golf course front"],
    [true, "HAC6170", "Location type ski in"],
    [true, "HAC6171", "Location type ski out"],
    [true, "HAC6173", "Location type town"],
    [true, "HAC6172", "Location type village"],
    [true, "ACC28", "Marina"],
    [true, "ACC29", "Market"],
    [true, "ACC31", "Mountain"],
    [false, "RMA223", "Mountain view"],
    [true, "ACC50", "Movie Theater"],
    [true, "ACC32", "Museum"],
    [false, "RMA224", "Ocean view"],
    [true, "HAC238", "Oceanfront"],
    [true, "HAC5058", "Open-air bath"],
    [true, "HAC6074", "Outdoor Dining Area: Private"],
    [true, "HAC6076", "Outdoor Dining Area: Screened-in"],
    [true, "HAC6077", "Outdoor Dining Area: Seats 10"],
    [true, "HAC6078", "Outdoor Dining Area: Seats 12"],
    [true, "HAC6079", "Outdoor Dining Area: Seats 20+"],
    [true, "HAC6075", "Outdoor Dining Area: Shared"],
    [true, "HAC6080", "Outdoor Furniture Area"],
    [true, "HAC6082", "Outdoor Furniture Area: Dining Area"],
    [true, "HAC6081", "Outdoor Furniture Area: Sun Loungers"],
    [true, "HAC5004", "Outdoor fireplace"],
    [true, "HAC5003", "Outdoor furniture"],
    [true, "ACC119", "Outdoor lanai gazebo covered"],
    [true, "HAC6175", "Outdoor snow sports gear"],
    [true, "HAC6176", "Outdoor veranda"],
    [true, "HAC6174", "Outdoor water sports gear"],
    [false, "RMA6053", "Park view"],
    [true, "HAC5078", "Picnic area"],
    [false, "RMA6013", "Pool view"],
    [true, "HAC5037", "Private beach area"],
    [false, "RMA6124", "Private yard"],
    [false, "RMA5191", "Quiet street view"],
    [true, "ACC39", "Recreation center"],
    [true, "ACC40", "Resort"],
    [true, "ACC41", "Restaurant"],
    [true, "ACC42", "River"],
    [false, "RMA6052", "River view"],
    [true, "HAC6087", "Riverfront"],
    [true, "ACC123", "Rural"],
    [false, "RMA5108", "Sea View"],
    [true, "HAC6091", "Seafront"],
    [true, "ACC33", "Seaocean"],
    [true, "ACC45", "Skilift"],
    [true, "HAC334", "Summer terrace"],
    [true, "HAC5076", "Sun loungers or beach chairs"],
    [true, "HAC5007", "Sun terrace"],
    [true, "HAC5077", "Sun umbrellas"],
    [true, "HAC5093", "Temporary art galleries"],
    [true, "HAC5006", "Terrace"],
    [false, "RMA5081", "View"],
    [true, "ACC54", "Water park"],
    [true, "RMA6017", "Water view"],
    [true, "ACC55", "Waterfront"],
    [true, "ACC56", "Winery Tours"],
    [true, "ACC57", "Zoo"],
  ]],
  ["Pool and Spa", [
    [true, "HAC5132", "Back massage"],
    [true, "HAC5148", "Body Treatments"],
    [true, "HAC5149", "Body scrub"],
    [true, "HAC5150", "Body wrap"],
    [true, "RST129", "Children's pool"],
    [true, "HAC5135", "Couples massage"],
    [true, "HAC5139", "Facial treatments"],
    [true, "HAC5122", "Fence around pool"],
    [true, "HAC6067", "Fitness Center: Access to community facilities"],
    [true, "HAC6068", "Fitness Center: Private"],
    [true, "HAC6184", "Fitness Room"],
    [true, "HAC345", "Fitness center"],
    [true, "HAC5090", "Fitness/spa locker rooms"],
    [true, "HAC5134", "Foot massage"],
    [true, "HAC5138", "Full body massage"],
    [true, "HAC5137", "Hand massage"],
    [true, "HAC5136", "Head massage"],
    [true, "HAC348", "Health and beauty services"],
    [true, "HAC49", "Heated pool"],
    [false, "RMA5014", "Hot Tub"],
    [true, "RST104", "Hot tub"],
    [true, "HAC5111", "Indoor Swimming Pool (all year)"],
    [true, "HAC5112", "Indoor Swimming Pool (seasonal)"],
    [true, "HAC54", "Indoor pool"],
    [false, "RMA5158", "Infinity pool"],
    [true, "HAC55", "Jacuzzi"],
    [true, "HAC5151", "Light therapy"],
    [true, "HAC61", "Massage services"],
    [true, "HAC5133", "Neck massage"],
    [true, "HAC5109", "Outdoor Swimming Pool (all year)"],
    [true, "HAC5110", "Outdoor Swimming Pool (seasonal)"],
    [true, "HAC66", "Outdoor pool"],
    [true, "HAC5118", "Plunge pool"],
    [true, "HAC71", "Pool"],
    [true, "HAC5119", "Pool bar"],
    [false, "RMA5165", "Pool cover"],
    [true, "HAC5121", "Pool cover"],
    [false, "RMA5163", "Pool towels"],
    [true, "HAC5069", "Pool towels"],
    [false, "RMA5159", "Pool with view"],
    [true, "HAC5116", "Pool with view"],
    [true, "HAC6086", "Pool: Community Access"],
    [true, "HAC6084", "Pool: Infinity Edge"],
    [true, "HAC6085", "Pool: Saltwater"],
    [false, "RMA5157", "Rooftop pool"],
    [true, "HAC5114", "Rooftop pool"],
    [false, "RMA5161", "Salt-water pool"],
    [true, "HAC79", "Sauna"],
    [false, "RMA5092", "Sauna"],
    [true, "HAC6090", "Sauna: En-suite"],
    [true, "HAC6088", "Sauna: Private"],
    [true, "HAC6089", "Sauna: Shared"],
    [false, "RMA5164", "Shallow end"],
    [true, "HAC5120", "Shallow end pool"],
    [true, "HAC83", "Solarium"],
    [true, "HAC5044", "Spa & Wellness Centre"],
    [true, "HAC5080", "Spa Facilities"],
    [true, "HAC5082", "Spa lounge/relaxation area"],
    [true, "HAC5084", "Spa/wellness packages"],
    [true, "HAC86", "Steam bath"],
    [true, "HAC6095", "Steam room"],
    [true, "HAC5154", "Swimming pool"],
    [true, "HAC5113", "Swimming pool toys"],
    [true, "HAC246", "Thalassotherapy"],
    [true, "HAC5157", "Towels Changed Upon Request"],
    [false, "RMA5160", "heated pool"],
  ]],
  ["Room Amenities", [
    [false, "RMA5185", "Adapter"],
    [false, "RMA6136", "Air Conditioning: Central"],
    [false, "RMA6138", "Air Conditioning: In rooms"],
    [false, "RMA6137", "Air Conditioning: Partial"],
    [false, "RMA2", "Air conditioning"],
    [false, "RMA126", "Air conditioning individually controlled in room"],
    [false, "RMA5115", "Allergy-Free"],
    [false, "RMA6139", "Baby Crib"],
    [false, "RMA5145", "Baby safety gates"],
    [false, "RMA7", "Balcony"],
    [false, "RMA6129", "Balcony: City View"],
    [false, "RMA6128", "Balcony: Garden View"],
    [false, "RMA6131", "Balcony: Mountain View"],
    [false, "RMA6130", "Balcony: Ocean View"],
    [false, "RMA6142", "Barbeque Grill: Charcoal"],
    [false, "RMA6140", "Barbeque Grill: Gas"],
    [false, "RMA6141", "Barbeque Grill: Propane"],
    [false, "RMA8", "Barbeque grills"],
    [false, "RMA9", "Bath tub with spray jets"],
    [false, "RMA5167", "Bottle of water"],
    [false, "RMA6059", "Carpeted floor"],
    [false, "RMA157", "Ceiling fan"],
    [false, "RMA230", "Chair provided with desk"],
    [false, "RMA6104", "Changing table"],
    [false, "RMA5142", "Child safety socket covers"],
    [false, "RMA5127", "Children highchair"],
    [false, "RMA279", "Children's playpen"],
    [false, "RMA6083", "Childrens dinnerware"],
    [false, "RMA6084", "Children’s books and toys"],
    [false, "RMA5169", "Chocolate/cookies"],
    [false, "RMA6066", "Cleaning Included"],
    [false, "RMA162", "Closets in room"],
    [false, "RMA5138", "Clothes Rack"],
    [false, "RMA5140", "Clothes drying rack"],
    [false, "RMA5120", "Coffee Machine"],
    [false, "RMA207", "Complimentary high speed internet in room"],
    [false, "RMA6103", "Cooking basics"],
    [false, "RMA25", "Cordless phone"],
    [false, "RMA28", "Desk"],
    [false, "RMA133", "Desk with electrical outlet"],
    [false, "RMA29", "Desk with lamp"],
    [false, "RMA6064", "Detached"],
    [false, "RMA5085", "Dining Area"],
    [false, "RMA6092", "Dining Highchair"],
    [false, "RMA5126", "Dining Table"],
    [false, "RMA6094", "Dining room"],
    [false, "RMA256", "Dining room seats"],
    [false, "RMA6095", "Dining spices"],
    [false, "RMA32", "Dishwasher"],
    [false, "RMA5041", "Dressing room"],
    [false, "RMA6034", "Dryer"],
    [false, "RMA5206", "Earplugs"],
    [false, "RMA5086", "Electric Kettle"],
    [false, "RMA5117", "Electric blankets"],
    [false, "RMA6154", "Entertainment Books"],
    [false, "RMA6155", "Entertainment Toys"],
    [false, "RMA6101", "Ethernet connection"],
    [false, "RMA5039", "Extra long beds (> 2 meter)"],
    [false, "RMA6100", "Extra pillows and blankets"],
    [false, "RMA5186", "Feather pillow"],
    [false, "RMA41", "Fireplace"],
    [false, "RMA6081", "Fireplace guards"],
    [false, "RMA6134", "Fireplace: Electric"],
    [false, "RMA6133", "Fireplace: Gas"],
    [false, "RMA6132", "Fireplace: Wood burning"],
    [false, "RMA135", "Foam pillows"],
    [false, "RMA46", "Free movies/video"],
    [false, "RMA205", "Free newspaper"],
    [false, "RMA6123", "Freezer"],
    [false, "RMA5168", "Fruits"],
    [false, "RMA47", "Full kitchen"],
    [false, "RMA49", "Grecian tub"],
    [false, "RMA6035", "Hangers"],
    [false, "RMA166", "Heating"],
    [false, "RMA6126", "High-Speed Wifi"],
    [false, "RMA6088", "House cleaning optional"],
    [false, "RMA186", "Hypoallergenic bed"],
    [false, "RMA5188", "Hypoallergenic pillow"],
    [false, "RMA6146", "In-unit Washer"],
    [false, "RMA6158", "Indoor Fireplace"],
    [false, "RMA5073", "Interconnecting Room(s) available"],
    [false, "RMA5002", "Internet facilities"],
    [false, "RMA55", "Iron"],
    [false, "RMA56", "Ironing board"],
    [false, "RMA59", "Kitchen"],
    [false, "RMA6145", "Kitchen Essentials"],
    [false, "RMA60", "Kitchen supplies"],
    [false, "RMA61", "Kitchenette"],
    [false, "RMA5089", "Kitchenware"],
    [false, "RMA6036", "Laptop Friendly Workspace"],
    [false, "RMA5074", "Laptop Safe Box"],
    [false, "RMA64", "Large desk"],
    [false, "RMA6058", "Linen"],
    [false, "RMA6042", "Living room"],
    [false, "RMA6073", "Lock on bedroom door"],
    [false, "RMA5200", "Lockers"],
    [false, "RMA234", "Luxury linen type"],
    [false, "RMA68", "Microwave"],
    [false, "RMA164", "Mini-refrigerator"],
    [false, "RMA69", "Minibar"],
    [false, "RMA258", "Mobile/cellular phones"],
    [false, "RMA6065", "Mosquito Net"],
    [false, "RMA72", "Multi-line phone"],
    [false, "RMA260", "Multiple closets"],
    [false, "RMA268", "Non-allergenic room"],
    [false, "RMA5187", "Non-feather pillow"],
    [false, "RMA6046", "Outdoor dining area"],
    [false, "RMA6045", "Outdoor furniture"],
    [false, "RMA6076", "Outlet covers"],
    [false, "RMA77", "Oven"],
    [false, "RMA5181", "Pajamas"],
    [false, "RMA6061", "Parquet Floor"],
    [false, "RMA6039", "Patio"],
    [false, "RMA6127", "Patio/Balcony"],
    [false, "RMA231", "Pillow top mattress"],
    [false, "RMA269", "Pillow type"],
    [false, "RMA6135", "Pizza Oven"],
    [false, "RMA81", "Plates and bowls"],
    [false, "RMA280", "Plunge pool"],
    [false, "RMA6102", "Pocket wifi"],
    [false, "RMA6144", "Premium Linens & Towels"],
    [false, "RMA6157", "Private Dock"],
    [false, "RMA5207", "Private curtain"],
    [false, "RMA245", "Private pool"],
    [false, "RMA5205", "Reading light"],
    [false, "RMA88", "Refrigerator"],
    [false, "RMA89", "Refrigerator with ice maker"],
    [false, "RMA91", "Rollaway bed"],
    [false, "RMA6082", "Room darkening shades"],
    [false, "RMA92", "Safe"],
    [false, "RMA5006", "Safe Deposit Box"],
    [false, "RMA262", "Safe large enough to accommodate a laptop"],
    [false, "RMA270", "Seating area with sofa/chair"],
    [false, "RMA6156", "Security System"],
    [false, "RMA6147", "Self-controlled heating/cooling system"],
    [false, "RMA6063", "Semi-Detached"],
    [false, "RMA94", "Separate closet"],
    [false, "RMA6010", "Separate entrance"],
    [false, "RMA98", "Silverware/utensils"],
    [false, "RMA99", "Sitting area"],
    [false, "RMA228", "Slippers"],
    [false, "RMA6074", "Smart lock"],
    [false, "RMA5184", "Socket near the bed"],
    [true, "HAC5046", "Soundproof-rooms"],
    [false, "RMA144", "Soundproofed room"],
    [false, "RMA5020", "Spa Bath"],
    [false, "RMA103", "Speaker phone"],
    [false, "RMA6078", "Stair gates"],
    [false, "RMA105", "Stove"],
    [false, "RMA6080", "Table corner guards"],
    [false, "RMA146", "Tables and chairs"],
    [false, "RMA107", "Telephone"],
    [false, "RMA194", "Telephone TDD/Textphone"],
    [false, "RMA108", "Telephone for hearing impaired"],
    [false, "RMA5123", "Terrace"],
    [false, "RMA6060", "Tiled floor"],
    [false, "RMA167", "Toaster"],
    [false, "RMA6001", "Towels available"],
    [false, "RMA5091", "Towels/Linens At Surcharge"],
    [false, "RMA5170", "Trash cans"],
    [false, "RMA111", "Trouser/Pant press"],
    [false, "RMA5094", "Tumble dryer (machine)"],
    [false, "RMA147", "Two-line phone"],
    [false, "RMA119", "Wake-up calls"],
    [false, "RMA5095", "Wardrobe/Closet"],
    [false, "RMA6033", "Washer"],
    [false, "RMA149", "Washer/dryer"],
    [false, "RMA5034", "Washing machine"],
    [false, "RMA6079", "Window guards"],
    [false, "RMA5171", "Wine glasses"],
    [false, "RMA5166", "Wine/champagne"],
    [false, "RMA6091", "Wood stove"],
    [false, "RMA5182", "Yukata"],
    [true, "HAC6025", "pack-n-play"],
  ]],
  ["Services", [
    [true, "HAC6050", "24/7 Support"],
    [true, "HAC6051", "Butler"],
    [true, "HAC6114", "Butler: Available for additional fee"],
    [true, "HAC6113", "Butler: On request"],
    [true, "HAC6052", "Concierge Services"],
    [true, "HAC6118", "Concierge Services: AM only"],
    [true, "HAC6119", "Concierge Services: PM only"],
    [true, "HAC6120", "Concierge Services: Weekends only"],
    [true, "HAC6160", "Deadbolt lock"],
    [true, "HAC6162", "Emergency exit route"],
    [true, "HAC6161", "Fire emergency contact"],
    [true, "HAC6123", "Gardener"],
    [true, "HAC6130", "House Manager"],
    [true, "HAC6053", "In-person Check-in"],
    [true, "HAC6131", "In-person Welcome"],
    [true, "HAC6163", "Medical emergency contact"],
    [true, "HAC6164", "Police emergency contact"],
    [true, "HAC5048", "Ticket service"],
  ]],
  ["Services & extras", [
    [true, "HAC7", "ATM/Cash machine"],
    [true, "HAC6036", "Beach essentials"],
    [true, "HAC5079", "Beauty Services"],
    [true, "HAC202", "Bicycle rentals"],
    [true, "HAC5000", "Breakfast in the room"],
    [true, "HAC5043", "Bridal Suite"],
    [true, "HAC6010", "Child toddler seat"],
    [true, "HAC6043", "City gateway"],
    [true, "HAC26", "Currency exchange"],
    [true, "HAC327", "Events ticket service"],
    [true, "HAC45", "Gift/News stand"],
    [true, "HAC5146", "Hair colouring"],
    [true, "HAC5145", "Hair cut"],
    [true, "HAC5040", "Hair dresser-beautician"],
    [true, "HAC5147", "Hair styling"],
    [true, "HAC5142", "Hair treatments"],
    [true, "HAC241", "Ironing board"],
    [true, "HAC5010", "Ironing service"],
    [true, "HAC283", "Luggage service"],
    [true, "HAC5141", "Make up services"],
    [true, "HAC5143", "Manicure"],
    [true, "HAC292", "Newspaper"],
    [true, "HAC5144", "Pedicure"],
    [true, "HAC5089", "Personal trainer"],
    [true, "HAC5001", "Public transport tickets"],
    [true, "HAC78", "Safe deposit box"],
    [true, "HAC5092", "Shuttle Service"],
    [true, "HAC6046", "Staffed Property"],
    [true, "HAC91", "Tour/sightseeing desk"],
    [true, "HAC5011", "Trouser press"],
    [true, "HAC5052", "Vending Machine (drinks)"],
    [true, "HAC98", "Vending machines"],
    [true, "HAC5140", "Waxing services"],
  ]],
  ["Shops", [
    [true, "HAC32", "Duty free shop"],
    [true, "HAC149", "Grocery shopping service available"],
    [true, "HAC6125", "Grocery shopping service available: Available for additional fee"],
    [true, "HAC6124", "Grocery shopping service available: On request"],
    [true, "HAC280", "Grocery store"],
    [true, "HAC5055", "Minimarket on site"],
    [true, "HAC5075", "On-site coffee house"],
    [true, "RST151", "Outlet shopping"],
    [true, "HAC122", "Shops and commercial services"],
  ]],
  ["Themes", [
    [true, "RST185", "Adventure"],
    [true, "HAC6167", "Attractions theme parks"],
    [true, "RST172", "Farm holidays"],
    [true, "RST173", "Historic"],
    [true, "RST175", "Historic"],
    [true, "RST186", "Rural countryside retreats"],
    [true, "RST176", "Tourist attractions"],
  ]],
  ["Transportation", [
    [true, "HAC5123", "Airport Shuttle (surcharge)"],
    [true, "HAC282", "Airport shuttle service"],
    [true, "HAC15", "Car rental desk"],
    [true, "HAC6014", "Cars"],
    [true, "HAC6185", "Chauffeur"],
    [true, "HAC41", "Free airport shuttle"],
    [true, "HAC6069", "Heli-pad"],
    [true, "HAC5152", "Shuttle Service (free)"],
    [true, "HAC5153", "Shuttle Service (surcharge)"],
  ]],
]).forEach(([category, amenities]) => {
  for (let i = 0, len = amenities.length; i < len; ++i) {
    const [resort, id, name] = amenities[i]
    const [target, klass] = resort
      ? [RESORT_AMENITIES, ResortAmenity]
      : [ROOM_AMENITIES, RoomAmenity]

    let byId = target.get(category)
    if (!byId) {
      byId = new Map<string, Amenity>()
      target.set(category, byId)
    }

    byId.set(id, new klass(id, name, category))
  }
})
